(function(){
'use strict';
if(!window.pdfjsLib||!window.XLSX)return;
const NONWORK=new Set(['F','FER','AF','AB','AL','FF','FC','NC','AE']),FLEX=new Set(['D']),CODE=/^(?:T\d{1,2}|F|FER|AF|AB|AL|FF|FC|NC|AE|D)$/i;
const MONTHS={JANEIRO:0,FEVEREIRO:1,MARCO:2,MARÇO:2,ABRIL:3,MAIO:4,JUNHO:5,JULHO:6,AGOSTO:7,SETEMBRO:8,OUTUBRO:9,NOVEMBRO:10,DEZEMBRO:11};
const norm=v=>String(v??'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toUpperCase().replace(/[^A-Z0-9 ]/g,' ').replace(/\s+/g,' ').trim();
const iso=(y,m,d)=>`${y}-${String(m+1).padStart(2,'0')}-${String(d).padStart(2,'0')}`;
const br=v=>{const m=String(v).match(/(\d{2})\/(\d{2})\/(\d{4})/);return m?`${m[3]}-${m[2]}-${m[1]}`:null};
const fmtDate=v=>v?v.split('-').reverse().join('/'):'—';
const pct=(v,d=1)=>`${(v*100).toFixed(d).replace('.',',')}%`;
const mins=t=>{const [h,m]=String(t).split(':').map(Number);return h*60+m};
const timeDiff=(a,b)=>{const d=Math.abs(mins(a)-mins(b));return Math.min(d,1440-d)};
function detectStore(text){const m=String(text).match(/\bML\s*0*(\d{1,3})\b/i);if(m)return`ML${String(+m[1]).padStart(2,'0')}`;const l=String(text).match(/\bLOJA\s*0*(\d{1,3})\b/i);return l?`ML${String(+l[1]).padStart(2,'0')}`:null}
function storesIn(text){return[...String(text).matchAll(/\bML\s*0*(\d{1,3})\b/gi)].map(m=>`ML${String(+m[1]).padStart(2,'0')}`)}
function detectMonthYear(text){const n=norm(text);for(const [name,month] of Object.entries(MONTHS)){let m=n.match(new RegExp(`\\b${norm(name)}\\s+(20\\d{2})\\b`));if(m)return{month,year:+m[1]};m=n.match(new RegExp(`\\b(20\\d{2})\\s+${norm(name)}\\b`));if(m)return{month,year:+m[1]}}return{month:null,year:null}}
function buildDates(days,month,year){if(month==null||!year||!days.length)return[];let m=month,y=year,p=days[0];return days.map((d,i)=>{if(i&&d<p){m++;if(m>11){m=0;y++}}p=d;return iso(y,m,d)})}
function makeRows(items,tol=2.5){const rows=[];for(const it of items.slice().sort((a,b)=>b.y-a.y||a.x-b.x)){let r=rows.find(x=>Math.abs(x.y-it.y)<tol);if(!r){r={y:it.y,items:[]};rows.push(r)}r.items.push(it)}for(const r of rows){r.items.sort((a,b)=>a.x-b.x);r.text=r.items.map(x=>x.text).join(' ')}rows.sort((a,b)=>b.y-a.y);return rows}
async function pdfPages(file){const bytes=new Uint8Array(await file.arrayBuffer()),pdf=await pdfjsLib.getDocument({data:bytes}).promise,pages=[];for(let p=1;p<=pdf.numPages;p++){const page=await pdf.getPage(p),tc=await page.getTextContent(),items=tc.items.filter(i=>i.str&&i.str.trim()).map(i=>({text:i.str.trim(),x:i.transform[4],y:i.transform[5],w:i.width||0})),rows=makeRows(items);pages.push({page,pdfPage:page,items,rows,text:rows.map(r=>r.text).join('\n'),source:'text'})}return pages}
async function ocrPage(page,index,onProgress){if(!window.Tesseract)throw new Error('PDF de escala sem camada de texto e OCR indisponível.');const vp=page.getViewport({scale:2}),canvas=document.createElement('canvas');canvas.width=Math.ceil(vp.width);canvas.height=Math.ceil(vp.height);await page.render({canvasContext:canvas.getContext('2d'),viewport:vp}).promise;const r=await Tesseract.recognize(canvas,'por+eng',{logger:m=>{if(m.status==='recognizing text')onProgress?.(`OCR página ${index}: ${Math.round((m.progress||0)*100)}%`)}});const words=(r.data.words||[]).filter(w=>w.text&&w.confidence>=45).map(w=>({text:w.text.trim(),x:w.bbox.x0/2,y:(vp.height-w.bbox.y1)/2,w:(w.bbox.x1-w.bbox.x0)/2})),rows=makeRows(words,5);return{page:index,pdfPage:page,items:words,rows,text:rows.map(r=>r.text).join('\n'),source:'ocr'}}
async function schedulePages(file,onProgress){const pages=await pdfPages(file),useful=pages.reduce((n,p)=>n+p.items.length,0),grid=pages.some(p=>/\bNOME\b/i.test(p.text)&&/\bCARGO\b/i.test(p.text));if(useful>=80&&grid)return pages;const out=[];for(let i=0;i<pages.length;i++)out.push(await ocrPage(pages[i].pdfPage,i+1,onProgress));return out}
function parseLegend(text){const out=new Map(),s=String(text);for(const re of [/\b(T\d{1,2})\s*(?:\||-|:)?\s*([0-2]\d:[0-5]\d)\s*(?:A|À|AS|ÀS|-)\s*([0-2]\d:[0-5]\d)/gi,/\b(T\d{1,2})\b[^\n]{0,40}?([0-2]\d:[0-5]\d)[^\n]{0,18}?([0-2]\d:[0-5]\d)/gi])for(const m of s.matchAll(re)){const k=norm(m[1]);if(!out.has(k))out.set(k,{start:m[2],end:m[3]})}return out}
function mergeTurns(a,b){for(const[k,v]of b)if(!a.has(k))a.set(k,v);return a}
function primaryStore(votes,hint){if(hint)votes.set(hint,(votes.get(hint)||0)+4);const list=[...votes].sort((a,b)=>b[1]-a[1]);if(!list.length)return{store:hint||null,candidates:[],ambiguous:false};const total=list.reduce((n,x)=>n+x[1],0),top=list[0],second=list[1],share=top[1]/Math.max(1,total),ambiguous=!!(second&&second[1]>=10&&second[1]/top[1]>=.82&&share<.60);return{store:top[0],candidates:list.map(([store,score])=>({store,score})),ambiguous}}
async function parsePointFile(file){const pages=await pdfPages(file),out={store:null,periodStart:null,periodEnd:null,employees:new Map(),quality:{}},votes=new Map(),hint=detectStore(file.name);let cur=null,daily=false;const vote=(s,w)=>s&&votes.set(s,(votes.get(s)||0)+w);for(const pg of pages)for(const r of pg.rows){const line=r.text,pm=line.match(/Espelho\s+do\s+Ponto\s+(\d{2}\/\d{2}\/\d{4})\s*-\s*(\d{2}\/\d{2}\/\d{4})/i);if(pm){out.periodStart=br(pm[1]);out.periodEnd=br(pm[2])}if(/Matr[ií]cula\s*:/i.test(line)&&/Nome\s*:/i.test(line)){const name=(line.match(/Nome\s*:\s*(.*?)(?=\s+(?:Chapa|Admiss[aã]o)\s*:|$)/i)||[])[1],reg=(line.match(/Matr[ií]cula\s*:\s*(.*?)(?=\s+Nome\s*:|$)/i)||[])[1];if(name){const key=norm(name);if(!out.employees.has(key))out.employees.set(key,{name:name.trim(),key,registration:(reg||'').trim(),cargo:'NÃO IDENTIFICADO',days:new Map()});cur=out.employees.get(key);daily=false}continue}const refs=storesIn(line);if(refs.length){const labeled=/DEPART|DEPTO|LOTA[CÇ][AÃ]O|FILIAL|UNIDADE|CENTRO\s*DE\s*CUSTO|C\.C\./i.test(line),weight=labeled?5:(cur?1:2);refs.forEach(s=>vote(s,weight));if(cur&&labeled)vote(refs[0],2)}if(!cur)continue;const cargo=(line.match(/^Fun[cç][aã]o\s*:\s*(?:\d+\s*-\s*)?(.*?)(?=\s+C\.C\.|\s+CPF\s*:|$)/i)||[])[1];if(cargo)cur.cargo=norm(cargo);if(/^Data\s+Dia\s+1a\s+E\./i.test(line)){daily=true;continue}if(/^Hor[aá]rios\b/i.test(line)||/^(?:C[oó]digo\s+Descri[cç][aã]o|Assinatura)/i.test(line)){daily=false;continue}if(!daily)continue;const dm=line.match(/^(\d{2}\/\d{2}\/\d{4})\b/);if(!dm)continue;const marks=[...line.matchAll(/\b([0-2]\d:[0-5]\d)\s*(?:O|I|P)\b/g)].map(m=>m[1]);cur.days.set(br(dm[1]),{firstEntry:marks[0]||null,marks})}const chosen=primaryStore(votes,hint);out.store=chosen.store;out.quality.storeCandidates=chosen.candidates;if(!out.employees.size)throw new Error('Espelho: funcionários não reconhecidos.');if(!out.periodStart||!out.periodEnd)throw new Error('Espelho: período não reconhecido.');if(!out.store)throw new Error('Espelho: loja não reconhecida.');if(chosen.ambiguous)throw new Error(`Espelho: loja realmente ambígua entre ${chosen.candidates.slice(0,2).map(x=>x.store).join(' e ')}.`);return out}
function headerCandidates(p){return p.rows.filter(r=>/\bNOME\b/i.test(r.text)&&/\bCARGO\b/i.test(r.text))}
function mergeEmployee(map,emp){const old=map.get(emp.key);if(!old){map.set(emp.key,emp);return}for(const[d,v]of emp.days)if(!old.days.has(d))old.days.set(d,v)}
function parseSchedulePdfPages(pages){const out={source:pages.some(p=>p.source==='ocr')?'pdf-ocr':'pdf',store:null,periodStart:null,periodEnd:null,employees:new Map(),turns:new Map(),quality:{source:pages.some(p=>p.source==='ocr')?'ocr':'text'}},full=pages.map(p=>p.text).join('\n');for(const p of pages){const top=p.rows.slice(0,Math.max(10,Math.ceil(p.rows.length*.25))).map(r=>r.text).join(' ');if(!out.store)out.store=detectStore(top);mergeTurns(out.turns,parseLegend(p.text))}if(!out.store)out.store=detectStore(full);let my={month:null,year:null};for(const p of pages){my=detectMonthYear(p.rows.slice(0,Math.max(12,Math.ceil(p.rows.length*.28))).map(r=>r.text).join(' '));if(my.month!=null)break}if(my.month==null)throw new Error('Escala PDF: mês/ano não reconhecido no cabeçalho.');for(const p of pages)for(const hdr of headerCandidates(p)){const cargoIt=hdr.items.find(i=>norm(i.text)==='CARGO');if(!cargoIt)continue;let days=p.items.filter(i=>Math.abs(i.y-hdr.y)<18&&/^\d{1,2}$/.test(i.text)&&+i.text>=1&&+i.text<=31&&i.x>cargoIt.x+20).sort((a,b)=>a.x-b.x),uniq=[];for(const d of days)if(!uniq.some(x=>Math.abs(x.x-d.x)<3))uniq.push(d);days=uniq;if(days.length<20)continue;const dates=buildDates(days.map(d=>+d.text),my.month,my.year),first=days[0].x,last=days.at(-1).x,spacing=(last-first)/Math.max(1,days.length-1),tol=Math.max(6,spacing*.55);for(const row of p.rows){if(row.y>=hdr.y-3)continue;const codes=row.items.filter(i=>i.x>=first-tol&&i.x<=last+tol&&CODE.test(norm(i.text)));if(codes.length<5)continue;const name=row.items.filter(i=>i.x<cargoIt.x-3).map(i=>i.text).join(' ').trim();if(!name||norm(name)==='NOME')continue;const cargo=row.items.filter(i=>i.x>=cargoIt.x-3&&i.x<first-tol).map(i=>i.text).join(' ').trim(),emp={name,key:norm(name),cargo:norm(cargo)||'NÃO IDENTIFICADO',days:new Map()};for(const ci of codes){let bi=-1,bd=Infinity;days.forEach((d,j)=>{const z=Math.abs(d.x-ci.x);if(z<bd){bd=z;bi=j}});if(bi>=0&&bd<=tol&&dates[bi]){const code=norm(ci.text),turn=out.turns.get(code);emp.days.set(dates[bi],{code,start:turn?.start||null})}}if(emp.days.size>=5)mergeEmployee(out.employees,emp)}}if(!out.store)throw new Error('Escala PDF: loja não reconhecida.');if(!out.employees.size)throw new Error('Escala PDF: matriz Nome × Dias não reconhecida.');const ds=[...out.employees.values()].flatMap(e=>[...e.days.keys()]).sort();out.periodStart=ds[0];out.periodEnd=ds.at(-1);return out}
function cellText(v){return v==null?'':v instanceof Date?v.toISOString():String(v).trim()}
function serial(v){if(typeof v!=='number'||v<30000)return null;const o=XLSX.SSF.parse_date_code(v);return o?iso(o.y,o.m-1,o.d):null}
function cellDate(v){if(v instanceof Date&&!isNaN(v))return iso(v.getFullYear(),v.getMonth(),v.getDate());return serial(v)||br(v)}
function safeRows(ws,maxRows=520,maxCols=430,raw=true){if(!ws||!ws['!ref'])return[];const rg=XLSX.utils.decode_range(ws['!ref']),er=Math.min(rg.e.r,rg.s.r+maxRows-1),ec=Math.min(rg.e.c,rg.s.c+maxCols-1);return XLSX.utils.sheet_to_json(ws,{header:1,defval:'',raw,range:{s:rg.s,e:{r:er,c:ec}}})}
function locateGrid(rows){for(let r=0;r<Math.min(rows.length,120);r++)for(let c=0;c<Math.min((rows[r]||[]).length,80);c++)if(norm(cellText(rows[r][c]))==='NOME')for(let rr=Math.max(0,r-2);rr<=Math.min(rows.length-1,r+2);rr++)for(let cc=0;cc<Math.min((rows[rr]||[]).length,80);cc++)if(norm(cellText(rows[rr][cc]))==='CARGO')return{nameRow:r,nameCol:c,cargoRow:rr,cargoCol:cc};return null}
function bestDates(rows,g){let best=null;for(let r=Math.max(0,Math.min(g.nameRow,g.cargoRow)-5);r<=Math.min(rows.length-1,Math.max(g.nameRow,g.cargoRow)+5);r++){const cs=[];let real=0;for(let c=Math.max(g.nameCol,g.cargoCol)+1;c<Math.min((rows[r]||[]).length,430);c++){const d=cellDate(rows[r][c]),n=+cellText(rows[r][c]);if(d){cs.push({c,date:d});real++}else if(Number.isInteger(n)&&n>=1&&n<=31)cs.push({c,day:n})}const score=real*5+cs.length;if(!best||score>best.score)best={candidates:cs,realDates:real,score}}return best}
function workbookLegend(wb,preferred){const out=new Map(),names=[preferred,'Escala Mensal','Escala Ponto','Andar no Tempo',...wb.SheetNames].filter((x,i,a)=>x&&a.indexOf(x)===i);for(const n of names){const ws=wb.Sheets[n];if(!ws)continue;for(const row of safeRows(ws,260,220,false))mergeTurns(out,parseLegend(row.map(cellText).join(' ')));if(out.size>=30)break}return out}
function workbookStore(wb,preferred){for(const n of [preferred,'Escala Mensal','Escala Ponto','Configuração',...wb.SheetNames.slice(0,4)]){const ws=wb.Sheets[n];if(!ws)continue;const s=detectStore(safeRows(ws,30,100,false).map(r=>r.join(' ')).join('\n'));if(s)return s}return null}
function parseScheduleWorkbook(buffer){const wb=XLSX.read(buffer,{type:'array',cellDates:true,cellFormula:true}),priority=['Andar no Tempo','Escala Ponto','Escala Mensal'],cand=[];for(const n of [...priority,...wb.SheetNames].filter((x,i,a)=>a.indexOf(x)===i)){const ws=wb.Sheets[n];if(!ws)continue;const rows=safeRows(ws),g=locateGrid(rows);if(!g)continue;const dr=bestDates(rows,g);if(!dr||dr.candidates.length<20)continue;const pri=n==='Andar no Tempo'?50000:n==='Escala Ponto'?10000:n==='Escala Mensal'?5000:0;cand.push({n,rows,g,dr,score:pri+dr.realDates*100+dr.candidates.length*10})}cand.sort((a,b)=>b.score-a.score);const ch=cand[0];if(!ch)throw new Error('Escala Excel: aba operacional não reconhecida.');const out={source:'excel',store:workbookStore(wb,ch.n),periodStart:null,periodEnd:null,employees:new Map(),turns:workbookLegend(wb,ch.n),quality:{realDates:ch.dr.realDates}},top=ch.rows.slice(0,18).map(r=>r.join(' ')).join(' ');let cols=ch.dr.candidates;if(!cols.some(x=>x.date)){const my=detectMonthYear(top),ds=buildDates(cols.map(x=>x.day),my.month,my.year);cols=cols.map((x,i)=>({c:x.c,date:ds[i]}))}else cols=cols.filter(x=>x.date);let blanks=0;for(let r=Math.max(ch.g.nameRow,ch.g.cargoRow)+1;r<ch.rows.length;r++){const row=ch.rows[r]||[],name=cellText(row[ch.g.nameCol]);if(!name){if(++blanks>14)break;continue}blanks=0;const key=norm(name);if(!key||/^(TOTAL|LEGENDA|GERENCIAL|CONSOLIDADO|MOTOR DE LANCAMENTOS)$/.test(key))continue;const emp={name:name.trim(),key,cargo:norm(cellText(row[ch.g.cargoCol]))||'NÃO IDENTIFICADO',days:new Map()};for(const d of cols){const code=norm(cellText(row[d.c]));if(CODE.test(code)){const t=out.turns.get(code);emp.days.set(d.date,{code,start:t?.start||null})}}if(emp.days.size>=5)mergeEmployee(out.employees,emp)}if(!out.store)throw new Error('Escala Excel: loja não reconhecida.');if(!out.employees.size)throw new Error('Escala Excel: colaboradores não reconhecidos.');const ds=[...out.employees.values()].flatMap(e=>[...e.days.keys()]).filter(Boolean).sort();out.periodStart=ds[0];out.periodEnd=ds.at(-1);return out}
async function parseScheduleFile(file,opts={}){const n=file.name.toLowerCase();if(n.endsWith('.pdf'))return parseSchedulePdfPages(await schedulePages(file,opts.onProgress));if(/\.(xlsx|xlsm|xls)$/.test(n))return parseScheduleWorkbook(await file.arrayBuffer());throw new Error('Formato de escala não suportado.')}
function lev(a,b){const m=a.length,n=b.length,d=Array.from({length:m+1},(_,i)=>[i]);for(let j=1;j<=n;j++)d[0][j]=j;for(let i=1;i<=m;i++)for(let j=1;j<=n;j++)d[i][j]=Math.min(d[i-1][j]+1,d[i][j-1]+1,d[i-1][j-1]+(a[i-1]===b[j-1]?0:1));return d[m][n]}
function tokenSim(a,b){const A=new Set(a.split(' ').filter(Boolean)),B=new Set(b.split(' ').filter(Boolean)),u=new Set([...A,...B]).size||1;return[...A].filter(x=>B.has(x)).length/u}
function matchEmp(s,points,used){if(points.has(s.key)&&!used.has(s.key))return{emp:points.get(s.key),key:s.key,mode:'exato'};const pref=[];for(const[k,p]of points){if(used.has(k))continue;const len=Math.min(k.length,s.key.length);if(len>=12&&(k.startsWith(s.key)||s.key.startsWith(k)))pref.push({emp:p,key:k,mode:'truncado'})}if(pref.length===1)return pref[0];const a=[];for(const[k,p]of points){if(used.has(k))continue;const ts=tokenSim(s.key,k),same=s.key.split(' ')[0]===k.split(' ')[0],sim=1-lev(s.key,k)/Math.max(1,s.key.length,k.length),score=sim*.7+ts*.3;if(same&&ts>=.75)a.push({emp:p,key:k,mode:'aproximado',score})}a.sort((x,y)=>y.score-x.score);return a[0]&&a[0].score>=.97&&(!a[1]||a[0].score-a[1].score>=.07)?a[0]:null}
function empMarks(e,s,t){let n=0;for(const[d,x]of e.days)if(d>=s&&d<=t)n+=x.marks.length;return n}
function pointMarks(p,s,t){let n=0;for(const e of p.employees.values())n+=empMarks(e,s,t);return n}
function analyze(point,schedule){if(point.store!==schedule.store)throw new Error(`Lojas diferentes: ponto ${point.store} × escala ${schedule.store}.`);const start=point.periodStart,end=point.periodEnd;if(!schedule.periodStart||schedule.periodStart>start||schedule.periodEnd<end)throw new Error(`A escala não cobre ${fmtDate(start)} a ${fmtDate(end)}.`);const used=new Set(),pairs=[],unmatched=[];let trunc=0,approx=0;for(const s of schedule.employees.values()){const m=matchEmp(s,point.employees,used);if(!m){unmatched.push(s.name);continue}used.add(m.key);if(m.mode==='truncado')trunc++;if(m.mode==='aproximado')approx++;pairs.push({s,p:m.emp})}let dev=0,nc=0,total=0,missing=0,unresolved=0,unknown=0,flexMarks=0,matched=0;const usedTurns=new Set(),cargoStats=new Map();for(const pair of pairs){const p=pair.p,s=pair.s;if(empMarks(p,start,end)>0)matched++;const cargo=p.cargo!=='NÃO IDENTIFICADO'?p.cargo:s.cargo;if(!cargoStats.has(cargo))cargoStats.set(cargo,{days:0,deviations:0,nc:0});const cs=cargoStats.get(cargo);for(const[date,pd]of p.days){if(date<start||date>end||!pd.marks.length)continue;const sd=s.days.get(date);if(!sd){missing+=pd.marks.length;continue}cs.days++;if(NONWORK.has(sd.code)){nc++;cs.nc++;total+=pd.marks.length;continue}if(FLEX.has(sd.code)){total+=pd.marks.length;flexMarks+=pd.marks.length;continue}if(/^T\d{1,2}$/.test(sd.code)){usedTurns.add(sd.code);if(!sd.start){unresolved+=pd.marks.length;continue}total+=pd.marks.length;if(pd.firstEntry&&timeDiff(sd.start,pd.firstEntry)>90){dev++;cs.deviations++}continue}unknown+=pd.marks.length}}
const all=pointMarks(point,start,end),pointOnly=[...point.employees.entries()].filter(([k])=>!used.has(k)).map(([,e])=>({name:e.name,marks:empMarks(e,start,end)})).filter(x=>x.marks>0),pointOnlyMarks=pointOnly.reduce((n,x)=>n+x.marks,0),people=[...point.employees.values()].filter(e=>empMarks(e,start,end)>0).length,coverage=all?total/all:0,nameCov=people?Math.min(1,matched/people):1,turnCov=usedTurns.size?[...usedTurns].filter(t=>schedule.turns.has(t)).length/usedTurns.size:1,parseQ=schedule.source==='excel'?(schedule.quality.realDates>=300?1:.97):(schedule.quality.source==='text'?1:.90),confidence=Math.max(0,Math.min(100,100*(.40*coverage+.25*nameCov+.20*turnCov+.15*parseQ)-approx*1.5));if(unresolved)throw new Error(`${unresolved} marcação(ões) usam turno T sem horário reconhecido.`);if(!total)throw new Error('Nenhuma marcação utilizável após o cruzamento.');if(coverage<.98){const reasons=[];if(pointOnlyMarks)reasons.push(`${pointOnlyMarks} de pessoa(s) não conciliada(s)`);if(missing)reasons.push(`${missing} sem célula de escala na data`);if(unknown)reasons.push(`${unknown} em código sem regra`);throw new Error(`Cobertura ${pct(coverage)} abaixo de 98%: ${all-total} de ${all} marcações ficaram fora da análise${reasons.length?` (${reasons.join('; ')})`:''}.`)}if(confidence<92)throw new Error(`Confiabilidade ${pct(confidence/100)} insuficiente. Cobertura ${pct(coverage)}; nomes ${pct(nameCov)}.`);const raw=1-(dev+10*nc)/total,adherence=Math.max(0,Math.min(1,raw));return{store:point.store,periodStart:start,periodEnd:end,adherence,confidence:confidence/100,coverage,deviations:dev,nonConformities:nc,totalMarks:total,totalPointMarks:all,matched,pointPeople:people,turnsUsed:[...usedTurns],turnsRecognized:schedule.turns.size,pointOnly,unmatchedSchedule:unmatched,cargoStats:[...cargoStats.entries()].map(([cargo,v])=>({cargo,...v})),source:schedule.source,truncatedMatches:trunc,approxMatches:approx,flexMarks,pointStoreCandidates:point.quality.storeCandidates||[]}}
window.ADERENCIA_BATCH_ENGINE={parsePointFile,parseScheduleFile,analyze,pct,fmtDate};
})();