(function(){
'use strict';
const $=id=>document.getElementById(id);
const rows=[];
let running=false;
const esc=s=>String(s||'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
function rowState(){return{id:crypto.randomUUID?crypto.randomUUID():Date.now()+'-'+Math.random(),point:null,schedule:null,status:'Aguardando arquivos',state:'idle',result:null}}
function addRow(){rows.push(rowState());render()}
function render(){const box=$('batchRows');if(!box)return;box.innerHTML=rows.map((r,i)=>`<article class="batch-row ${r.state}"><div class="batch-index">${i+1}</div><label class="batch-file">Espelho de ponto<input type="file" accept="application/pdf,.pdf" data-kind="point" data-id="${r.id}"><strong>${esc(r.point?.name||'Selecionar PDF')}</strong></label><label class="batch-file">Escala planejada<input type="file" accept="application/pdf,.pdf,.xlsx,.xlsm,.xls" data-kind="schedule" data-id="${r.id}"><strong>${esc(r.schedule?.name||'Selecionar escala')}</strong></label><div class="batch-status"><span>${esc(r.status)}</span>${r.result?`<strong>${r.result.store} • ${(r.result.adherence*100).toFixed(2).replace('.',',')}%</strong>`:''}</div><button class="batch-remove" data-remove="${r.id}" type="button" ${running?'disabled':''}>×</button></article>`).join('');$('batchCount').textContent=rows.length;$('batchReady').textContent=rows.filter(r=>r.point&&r.schedule).length;$('batchOk').textContent=rows.filter(r=>r.state==='ok').length;$('batchError').textContent=rows.filter(r=>r.state==='error').length;$('batchProcessBtn').disabled=running||!rows.some(r=>r.point&&r.schedule);$('batchSaveBtn').disabled=running||!rows.some(r=>r.result)}
function waitStatus(id,timeout=120000){return new Promise((resolve,reject)=>{const started=Date.now(),tick=()=>{const el=$(id),t=el?.textContent||'';if(el?.classList.contains('ok'))return resolve(t);if(el?.classList.contains('error'))return reject(new Error(t.replace(/^Erro:\s*/,'')||'Falha na leitura'));if(Date.now()-started>timeout)return reject(new Error('Tempo limite de processamento excedido.'));setTimeout(tick,120)};tick()})}
function setNativeFile(input,file){const dt=new DataTransfer();dt.items.add(file);input.files=dt.files;input.dispatchEvent(new Event('change',{bubbles:true}))}
async function processRow(r,index){r.state='working';r.status='Lendo espelho...';r.result=null;render();try{setNativeFile($('pointFile'),r.point);await waitStatus('pointStatus');r.status='Lendo escala...';render();setNativeFile($('scheduleFile'),r.schedule);await waitStatus('scheduleStatus',180000);r.status='Calculando aderência...';render();$('calculateBtn').click();await new Promise(res=>setTimeout(res,80));const a=window.ADERENCIA_LAST_ANALYSIS;if(!a)throw new Error('O motor bloqueou o resultado. Abra a Análise individual para consultar o diagnóstico.');r.result=JSON.parse(JSON.stringify(a));r.state='ok';r.status='Processado com sucesso';}catch(e){r.state='error';r.status=e.message||'Falha no processamento';}render()}
async function processAll(){if(running)return;const ready=rows.filter(r=>r.point&&r.schedule);if(!ready.length)return;running=true;$('batchProgress').classList.remove('hidden');$('batchProgressBar').style.width='0%';render();for(let i=0;i<ready.length;i++){await processRow(ready[i],i);$('batchProgressText').textContent=`${i+1} de ${ready.length} processadas`;$('batchProgressBar').style.width=`${((i+1)/ready.length)*100}%`;await new Promise(r=>setTimeout(r,30))}running=false;render()}
function saveAll(){const valid=rows.filter(r=>r.result);if(!valid.length||!window.ADERENCIA_HISTORY)return;const hist=window.ADERENCIA_HISTORY.load();let saved=0,updated=0;for(const r of valid){const a=r.result,d=new Date(`${a.periodEnd}T12:00:00`),month=d.getMonth()+1,year=d.getFullYear(),adherence=+(a.adherence*100).toFixed(2),idx=hist.findIndex(x=>x.store===a.store&&x.month===month&&x.year===year),prev=idx>=0?hist[idx]:null,row={store:a.store,month,year,adherence,bonus:prev?.bonus||false,bonusAt:prev?.bonusAt||null,savedAt:new Date().toISOString()};if(idx>=0){hist[idx]=row;updated++}else{hist.push(row);saved++}}window.ADERENCIA_HISTORY.saveAll(hist);window.ADERENCIA_HISTORY.notify();alert(`${saved} resultado(s) salvo(s) e ${updated} atualizado(s) no histórico.`)}
function clearDone(){for(let i=rows.length-1;i>=0;i--)if(rows[i].state==='ok')rows.splice(i,1);if(!rows.length)addRow();else render()}
document.addEventListener('change',e=>{const id=e.target?.dataset?.id,kind=e.target?.dataset?.kind;if(!id||!kind)return;const r=rows.find(x=>x.id===id);if(!r)return;r[kind]=e.target.files?.[0]||null;r.status=r.point&&r.schedule?'Pronto para processar':'Aguardando arquivos';r.state='idle';r.result=null;render()});
document.addEventListener('click',e=>{const rem=e.target?.dataset?.remove;if(rem&&!running){const i=rows.findIndex(x=>x.id===rem);if(i>=0)rows.splice(i,1);if(!rows.length)addRow();else render()}});
$('batchAddBtn')?.addEventListener('click',addRow);$('batchProcessBtn')?.addEventListener('click',processAll);$('batchSaveBtn')?.addEventListener('click',saveAll);$('batchClearBtn')?.addEventListener('click',clearDone);
addRow();
})();