(function(){
'use strict';
window.ADERENCIA_VERSION='v1.0 RC62';
const REQUIRED=[['pdfjsLib','leitor de PDF'],['XLSX','leitor de Excel']];
const OPTIONAL=[['jspdf','gerador de relatórios PDF']];
function setStatus(id,text){const e=document.getElementById(id);if(!e)return;e.textContent=text;e.classList.remove('muted','ok');e.classList.add('error')}
function storageOK(){try{const k='__aderencia_health__';localStorage.setItem(k,'1');localStorage.removeItem(k);return true}catch{return false}}
function check(){const missing=REQUIRED.filter(([k])=>!window[k]);const optional=OPTIONAL.filter(([k])=>!window[k]);window.ADERENCIA_HEALTH={ok:!missing.length&&storageOK(),missing:missing.map(x=>x[1]),optionalMissing:optional.map(x=>x[1]),storage:storageOK(),ocrMode:'explicit-on-demand',checkedAt:new Date().toISOString()};if(missing.length){const msg=`Não foi possível carregar ${missing.map(x=>x[1]).join(' e ')}. Este pacote usa bibliotecas online; verifique a conexão e reabra o index.html.`;setStatus('pointStatus',msg);setStatus('scheduleStatus',msg);document.getElementById('calculateBtn')?.setAttribute('disabled','disabled');alert(msg)}else if(!window.ADERENCIA_HEALTH.storage){alert('O navegador bloqueou o armazenamento local. A análise funcionará, mas o histórico não poderá ser salvo.')}else if(optional.length){console.warn('Recursos opcionais indisponíveis:',optional.map(x=>x[1]).join(', '))}}
function loadBatch(){if(document.querySelector('script[data-aderencia-batch]'))return;const s=document.createElement('script');s.src='batch.js';s.dataset.aderenciaBatch='1';s.defer=true;document.head.appendChild(s)}
window.addEventListener('error',e=>console.error('Erro global da aplicação:',e.error||e.message));check();const badge=document.querySelector('.privacy');if(badge)badge.textContent=`Processamento local no navegador • ${window.ADERENCIA_VERSION}`;
const ACTIVE=['runtime-cache-rc47.js','ocr-lazy-rc48.js','portable-storage.js','pdf-security-rc35.js','point-semantics.js','pdf-xlsx-compat-rc21.js','pdf-calendar-integrity-rc29.js','canonical-validation-rc35.js','schedule-hardening-rc51.js','schedule-adaptive-rc62.js','schedule-adaptive-rc61.js','schedule-monthly-bridge-rc53.js','schedule-rc59-compat-capture.js','schedule-real-xlsm-rc59.js','schedule-rc59-compat-guard.js','schedule-rc59-point-table-guard.js','schedule-provenance-guard-rc55.js','schedule-source-identity-guard-rc58.js','schedule-preprocess-rc52.js','pdf-store-header-guard-rc57.js','pdf-schedule-parser-rc57.js','monitor-export.js','divergence-dashboard-rc44.js','divergence-capture-rc20.js','divergence-help-rc42.js','layout-fixes-rc19.js','store-management.js','ui-final-rc35.js','network-led-panel-rc36.js','competence-integrity-rc38.js','region-view-integrity-rc38.js','period-controller-rc39.js','period-render-coherence-rc44.js','evolution-dashboard-rc39.js','regional-comparison-rc51.js','performance-rc42.js','divergence-audit-rc42.js','recurrence-dashboard-rc44.js','navigation-integrity-rc44.js','rc50-integrity-check.js'];
window.ADERENCIA_ACTIVE_MODULES=ACTIVE.slice();ACTIVE.forEach(src=>document.write(`<script src="${src}"><\/script>`));
document.addEventListener('DOMContentLoaded',()=>{const r=window.ADERENCIA_STORE_REGISTRY;if(r)r.importRegistry(r.load())});loadBatch();
})();