(function(){
'use strict';
if(!window.pdfjsLib||!window.XLSX)return;
const NONWORK=new Set(['F','FER','AF','AB','AL','FF','FC','NC','AE']);
const FLEX=new Set(['D']);
const CODE=/^(?:T\d{1,2}|F|FER|AF|AB|AL|FF|FC|NC|AE|D)$/i;
const MONTHS={JANEIRO:0,FEVEREIRO:1,MARCO:2,MARÇO:2,ABRIL:3,MAIO:4,JUNHO:5,JULHO:6,AGOSTO:7,SETEMBRO:8,OUTUBRO:9,NOVEMBRO:10,DEZEMBRO:11};
const $=id=>document.getElementById(id);
const norm=v=>String(v??'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toUpperCase().replace(/[^A-Z0-9 ]/g,' ').replace(/\s+/g,' ').trim();
const iso=(y,m,d)=>`${y}-${String(m+1).padStart(2,'0')}-${String(d).padStart(2,'0')}`;
const br=v=>{const m=String(v).match(/(\d{2})\/(\d{2})\/(\d{4})/);return m?`${m[3]}-${m[2]}-${m[1]}`:null};
const fmtDate=v=>v?v.split('-').reverse().join('/'):'—';
const mins=t=>{const [h,m]=String(t).split(':').map(Number);return h*60+m};
const timeDiff=(a,b)=>{const d=Math.abs(mins(a)-mins(b));return Math.min(d,1440-d)};
const pct=(v,d=1)=>`${(v*100).toFixed(d).replace('.',',')}%`;
function detectStore(text){const m=String(text).match(/\bML\s*0*(\d{1,3})\b/i);if(m)return`ML${String(+m[1]).padStart(2,'0')}`;const l=String(text).match(/\bLOJA\s*0*(\d{1,3})\b/i);return l?`ML${String(+l[1]).padStart(2,'0')}`:null}
function allStores(text){const out=[];for(const m of String(text).matchAll(/\bML\s*0*(\d{1,3})\b/gi))out.push(`ML${String(+m[1]).padStart(2,'0')}`);return out}
function detectMonthYear(text){const n=norm(text);for(const [name,month] of Object.entries(MONTHS)){let m=n.match(new RegExp(`\\b${norm(name)}\\s+(20\\d{2})\\b`));if(m)return{month,year:+m[1]};m=n.match(new RegExp(`\\b(20\\d{2})\\s+${norm(name)}\\b`));if(m)return{month,year:+m[1]}}return{month:null,year:null}}
function buildDates(days,month,year){if(month==null||!year||!days.length)return[];let m=month,y=year,p=days[0];return days.map((d,i)=>{if(i&&d<p){m++;if(m>11){m=0;y++}}p=d;return iso(y,m,d)})}
function parseLegendText(text){const out=new Map(),s=String(text).replace(/\r/g,'');for(const re of [/\b(T\d{1,2})\s*(?:\||-|:)?\s*([0-2]\d:[0-5]\d)\s*(?:A|À|AS|ÀS|-)\s*([0-2]\d:[0-5]\d)/gi,/\b(T\d{1,2})\b[^\n]{0,40}?([0-2]\d:[0-5]\d)[^\n]{0,18}?([0-2]\d:[0-5]\d)/gi])for(const m of s.matchAll(re)){const k=norm(m[1]);if(!out.has(k))out.set(k,{start:m[2],end:m[3]})}return out}
function mergeTurns(a,b){for(const[k,v]of b)if(!a.has(k))a.set(k,v);return a}
function makeRows(items,tol=2.5){const rows=[];for(const it of items.slice().sort((a,b)=>b.y-a.y||a.x-b.x)){let r=rows.find(x=>Math.abs(x.y-it.y)<tol);if(!r){r={y:it.y,items:[]};rows.push(r)}r.items.push(it)}for(const r of rows){r.items.sort((a,b)=>a.x-b.x);r.text=r.items.map(x=>x.text).join(' ')}rows.sort((a,b)=>b.y-a.y);return rows}
async function pdfTextPages(file){const bytes=new Uint8Array(await file.arrayBuffer()),pdf=await pdfjsLib.getDocument({data:bytes}).promise,pages=[];for(let p=1;p<=pdf.numPages;p++){const page=await pdf.getPage(p),tc=await page.getTextContent(),items=tc.items.filter(i=>i.str&&i.str.trim()).map(i=>({text:i.str.trim(),x:i.transform[4],y:i.transform[5],w:i.width||0})),rows=makeRows(items);pages.push({page:p,pdfPage:page,items,rows,text:rows.map(r=>r.text).join('\n'),source:'text'})}return pages}
async function ocrPage(page,index,onProgress){if(!window.Tesseract)throw new Error('PDF sem camada de texto e OCR indisponível. Verifique a conexão com a internet.');const vp=page.getViewport({scale:2}),canvas=document.createElement('canvas');canvas.width=Math.ceil(vp.width);canvas.height=Math.ceil(vp.height);await page.render({canvasContext:canvas.getContext('2d'),viewport:vp}).promise;const r=await Tesseract.recognize(canvas,'por+eng',{logger:m=>{if(m.status==='recognizing text')onProgress?.(`OCR • página ${index}: ${Math.round((m.progress||0)*100)}%`)}});const words=(r.data.words||[]).filter(w=>w.text&&w.confidence>=45).map(w=>({text:w.text.trim(),x:w.bbox.x0/2,y:(vp.height-w.bbox.y1)/2,w:(w.bbox.x1-w.bbox.x0)/2})),rows=makeRows(words,5);return{page:index,pdfPage:page,items:words,rows,text:rows.map(x=>x.text).join('\n'),source:'ocr'}}
async function schedulePdfPages(file,onProgress){const pages=await pdfTextPages(file),useful=pages.reduce((n,p)=>n+p.items.length,0),hasGrid=pages.some(p=>/\bNOME\b/i.test(p.text)&&/\bCARGO\b/i.test(p.text));if(useful>=80&&hasGrid)return pages;const out=[];for(let i=0;i<pages.length;i++)out.push(await ocrPage(pages[i].pdfPage,i+1,onProgress));return out}
function choosePrimaryStore(votes,fileHint){if(fileHint)votes.set(fileHint,(votes.get(fileHint)||0)+4);const list=[...votes].sort((a,b)=>b[1]-a[1]);if(!list.length)return{store:fileHint||null,candidates:[],ambiguous:false,source:fileHint?'arquivo':'nenhuma'};const total=list.reduce((n,x)=>n+x[1],0),top=list[0],second=list[1],share=top[1]/Math.max(1,total),ambiguous=!!(second&&second[1]>=8&&second[1]/top[1]>=.75&&share<.65);return{store:top[0],candidates:list.map(([store,score])=>({store,score})),ambiguous,source:fileHint===top[0]?'documento+arquivo':'documento'}}
function parsePointPages(pages,fileName=''){const hint=detectStore(fileName),out={type:'point',store:null,periodStart:null,periodEnd:null,employees:new Map(),quality:{rows:0,marks:0,storeCandidates:[],storeSource:null,storeAmbiguous:false}},votes=new Map();let cur=null,daily=false;const addVote=(store,w)=>{if(store)votes.set(store,(votes.get(store)||0)+w)};for(const pg of pages)for(const r of pg.rows){const line=r.text,pm=line.match(/Espelho\s+do\s+Ponto\s+(\d{2}\/\d{2}\/\d{4})\s*-\s*(\d{2}\/\d{2}\/\d{4})/i);if(pm){out.periodStart=br(pm[1]);out.periodEnd=br(pm[2])}if(/Matr[ií]cula\s*:/i.test(line)&&/Nome\s*:/i.test(line)){const name=(line.match(/Nome\s*:\s*(.*?)(?=\s+(?:Chapa|Admiss[aã]o)\s*:|$)/i)||[])[1],reg=(line.match(/Matr[ií]cula\s*:\s*(.*?)(?=\s+Nome\s*:|$)/i)||[])[1];if(name){const key=norm(name),registration=(reg||'').trim(),existing=out.employees.get(key);if(existing&&existing.registration&&registration&&existing.registration!==registration)throw new Error(`Espelho: existem dois colaboradores com o mesmo nome normalizado (${name.trim()}).`);if(!existing)out.employees.set(key,{name:name.trim(),key,registration,cargo:'NÃO IDENTIFICADO',store:null,days:new Map()});cur=out.employees.get(key);daily=false}continue}const stores=allStores(line);if(stores.length){const labeled=/DEPART|DEPTO|LOTA[CÇ][AÃ]O|FILIAL|UNIDADE|CENTRO\s*DE\s*CUSTO|C\.C\./i.test(line),w=labeled?4:(cur?1:2);for(const st of stores)addVote(st,w);if(cur&&labeled){cur.store=stores[0];addVote(stores[0],2)}}if(!cur)continue;const cargo=(line.match(/^Fun[cç][aã]o\s*:\s*(?:\d+\s*-\s*)?(.*?)(?=\s+C\.C\.|\s+CPF\s*:|$)/i)||[])[1];if(cargo)cur.cargo=norm(cargo);if(/^Data\s+Dia\s+1a\s+E\./i.test(line)){daily=true;continue}if(/^Hor[aá]rios\b/i.test(line)||/^(?:C[oó]digo\s+Descri[cç][aã]o|Assinatura)/i.test(line)){daily=false;continue}if(!daily)continue;const dm=line.match(/^(\d{2}\/\d{2}\/\d{4})\b/);if(!dm)continue;const marks=[...line.matchAll(/\b([0-2]\d:[0-5]\d)\s*(?:O|I|P)\b/g)].map(m=>m[1]),date=br(dm[1]);cur.days.set(date,{date,firstEntry:marks[0]||null,marks,raw:line});out.quality.rows++;out.quality.marks+=marks.length}
const chosen=choosePrimaryStore(votes,hint);out.store=chosen.store;out.quality.storeCandidates=chosen.candidates;out.quality.storeSource=chosen.source;out.quality.storeAmbiguous=chosen.ambiguous;if(!out.employees.size)throw new Error('Espelho: funcionários não reconhecidos.');if(!out.periodStart||!out.periodEnd)throw new Error('Espelho: período não reconhecido.');if(!out.store)throw new Error('Espelho: loja não reconhecida.');if(chosen.ambiguous)throw new Error(`Espelho: identificação de loja ambígua (${chosen.candidates.slice(0,3).map(x=>`${x.store}:${x.score}`).join(', ')}).`);return out}
function headerCandidates(page){return page.rows.filter(r=>/\bNOME\b/i.test(r.text)&&/\bCARGO\b/i.test(r.text))}
function mergeEmployee(target,emp){const existing=target.get(emp.key);if(!existing){target.set(emp.key,emp);return}let overlap=0;for(const[d,v]of emp.days){if(existing.days.has(d))overlap++;else existing.days.set(d,v)}if(overlap>=5)throw new Error(`Escala: nome duplicado com datas sobrepostas (${emp.name}).`)}
function parseSchedulePdf(pages){const full=pages.map(p=>p.text).join('\n'),out={type:'schedule',source:pages.some(p=>p.source==='ocr')?'pdf-ocr':'pdf',store:null,periodStart:null,periodEnd:null,employees:new Map(),turns:new Map(),quality:{source:pages.some(p=>p.source==='ocr')?'ocr':'text',headers:0,daySlots:0,codeCells:0,rows:0}};for(const p of pages){const top=p.rows.slice(0,Math.max(8,Math.ceil(p.rows.length*.25))).map(r=>r.text).join(' '),s=detectStore(top);if(s&&!out.store)out.store=s;mergeTurns(out.turns,parseLegendText(p.text))}if(!out.store)out.store=detectStore(full);let my={month:null,year:null};for(const p of pages){const top=p.rows.slice(0,Math.max(10,Math.ceil(p.rows.length*.28))).map(r=>r.text).join(' '),x=detectMonthYear(top);if(x.month!=null){my=x;break}}if(my.month==null)throw new Error('Escala PDF: mês/ano não reconhecido no cabeçalho.');for(const p of pages)for(const hdr of headerCandidates(p)){out.quality.headers++;const cargoIt=hdr.items.find(i=>norm(i.text)==='CARGO');if(!cargoIt)continue;let days=p.items.filter(i=>Math.abs(i.y-hdr.y)<18&&/^\d{1,2}$/.test(i.text)&&+i.text>=1&&+i.text<=31&&i.x>cargoIt.x+20).sort((a,b)=>a.x-b.x),uniq=[];for(const d of days)if(!uniq.some(x=>Math.abs(x.x-d.x)<3))uniq.push(d);days=uniq;if(days.length<20)continue;out.quality.daySlots=Math.max(out.quality.daySlots,days.length);const dates=buildDates(days.map(d=>+d.text),my.month,my.year),first=days[0].x,last=days.at(-1).x,spacing=days.length>1?(last-first)/(days.length-1):14,tol=Math.max(6,spacing*.55);for(const row of p.rows){if(row.y>=hdr.y-3)continue;const codes=row.items.filter(i=>i.x>=first-tol&&i.x<=last+tol&&CODE.test(norm(i.text)));if(codes.length<5)continue;const name=row.items.filter(i=>i.x<cargoIt.x-3).map(i=>i.text).join(' ').trim();if(!name||norm(name)==='NOME')continue;const cargo=row.items.filter(i=>i.x>=cargoIt.x-3&&i.x<first-tol).map(i=>i.text).join(' ').trim(),key=norm(name),emp={name,key,cargo:norm(cargo)||'NÃO IDENTIFICADO',days:new Map()};for(const ci of codes){let bi=-1,bd=Infinity;days.forEach((d,j)=>{const z=Math.abs(d.x-ci.x);if(z<bd){bd=z;bi=j}});if(bi>=0&&bd<=tol&&dates[bi]){const code=norm(ci.text),turn=out.turns.get(code);emp.days.set(dates[bi],{date:dates[bi],code,start:turn?.start||null});out.quality.codeCells++}}if(emp.days.size>=5){mergeEmployee(out.employees,emp);out.quality.rows++}}}if(!out.store)throw new Error('Escala PDF: loja não reconhecida.');if(!out.employees.size)throw new Error('Escala PDF: matriz Nome × Dias não reconhecida.');const dates=[...out.employees.values()].flatMap(e=>[...e.days.keys()]).sort();out.periodStart=dates[0]||null;out.periodEnd=dates.at(-1)||null;return out}
function cellText(v){return v==null?'':v instanceof Date?v.toISOString():String(v).trim()}
function serial(v){if(typeof v!=='number'||v<30000)return null;const o=XLSX.SSF.parse_date_code(v);return o?iso(o.y,o.m-1,o.d):null}
function cellDate(v){if(v instanceof Date&&!Number.isNaN(v.getTime()))return iso(v.getFullYear(),v.getMonth(),v.getDate());return serial(v)||br(v)}
function safeRows(ws,maxRows=520,maxCols=430,raw=true){if(!ws||!ws['!ref'])return[];const rg=XLSX.utils.decode_range(ws['!ref']),er=Math.min(rg.e.r,rg.s.r+maxRows-1),ec=Math.min(rg.e.c,rg.s.c+maxCols-1);return XLSX.utils.sheet_to_json(ws,{header:1,defval:'',raw,range:{s:rg.s,e:{r:er,c:ec}}})}
function locateGrid(rows){let best=null;for(let r=0;r<Math.min(rows.length,120);r++)for(let c=0;c<Math.min((rows[r]||[]).length,80);c++)if(norm(cellText(rows[r][c]))==='NOME'){let cargo=null;for(let rr=Math.max(0,r-2);rr<=Math.min(rows.length-1,r+2)&&!cargo;rr++)for(let cc=0;cc<Math.min((rows[rr]||[]).length,80);cc++)if(norm(cellText(rows[rr][cc]))==='CARGO'){cargo={r:rr,c:cc};break}if(cargo){const score=100-Math.abs(cargo.r-r)*5;if(!best||score>best.score)best={nameRow:r,nameCol:c,cargoRow:cargo.r,cargoCol:cargo.c,score}}}return best}
function bestDates(rows,g){let best=null;for(let r=Math.max(0,Math.min(g.nameRow,g.cargoRow)-5);r<=Math.min(rows.length-1,Math.max(g.nameRow,g.cargoRow)+5);r++){const cs=[];let real=0;for(let c=Math.max(g.nameCol,g.cargoCol)+1;c<Math.min((rows[r]||[]).length,430);c++){const v=rows[r][c],d=cellDate(v),n=+cellText(v);if(d){cs.push({c,date:d});real++}else if(Number.isInteger(n)&&n>=1&&n<=31)cs.push({c,day:n})}const sc=real*5+cs.length;if(!best||sc>best.score)best={r,candidates:cs,realDates:real,score:sc}}return best}
function workbookLegend(wb,preferred){const out=new Map(),names=[preferred,'Escala Mensal','Escala Ponto','Andar no Tempo',...wb.SheetNames].filter((x,i,a)=>x&&a.indexOf(x)===i);for(const n of names){const ws=wb.Sheets[n];if(!ws)continue;for(const row of safeRows(ws,260,220,false)){const line=row.map(cellText).filter(Boolean).join(' ');mergeTurns(out,parseLegendText(line));for(let i=0;i<row.length-1;i++)mergeTurns(out,parseLegendText(`${cellText(row[i])} ${cellText(row[i+1])}`))}if(out.size>=30)break}return out}
function workbookStore(wb,preferred){for(const n of [preferred,'Escala Mensal','Escala Ponto','Configuração',...wb.SheetNames.slice(0,4)]){const ws=wb.Sheets[n];if(!ws)continue;const t=safeRows(ws,30,100,false).map(r=>r.join(' | ')).join('\n'),s=detectStore(t);if(s)return s}return null}
function parseScheduleWorkbook(buffer){const wb=XLSX.read(buffer,{type:'array',cellDates:true,cellFormula:true,dense:false}),priority=['Andar no Tempo','Escala Ponto','Escala Mensal'],candidates=[];for(const n of [...priority,...wb.SheetNames].filter((x,i,a)=>a.indexOf(x)===i)){const ws=wb.Sheets[n];if(!ws)continue;const rows=safeRows(ws,520,430,true);if(!rows.length)continue;const g=locateGrid(rows);if(!g)continue;const dr=bestDates(rows,g);if(!dr||dr.candidates.length<20)continue;let codes=0;for(const row of rows.slice(Math.max(g.nameRow,g.cargoRow)+1,Math.max(g.nameRow,g.cargoRow)+130))for(const v of row)if(CODE.test(norm(cellText(v))))codes++;const pri=n==='Andar no Tempo'?50000:n==='Escala Ponto'?10000:n==='Escala Mensal'?5000:0,score=pri+dr.realDates*100+dr.candidates.length*10+codes;candidates.push({sheetName:n,rows,g,dr,score})}candidates.sort((a,b)=>b.score-a.score);const ch=candidates[0];if(!ch)throw new Error('Escala Excel: aba operacional não reconhecida.');const out={type:'schedule',source:'excel',sheet:ch.sheetName,store:workbookStore(wb,ch.sheetName),periodStart:null,periodEnd:null,employees:new Map(),turns:workbookLegend(wb,ch.sheetName),quality:{sheet:ch.sheetName,realDates:ch.dr.realDates,daySlots:ch.dr.candidates.length,rows:0,codeCells:0}};let cols=ch.dr.candidates;if(!cols.some(x=>x.date)){const top=ch.rows.slice(0,18).map(r=>r.join(' ')).join(' '),my=detectMonthYear(top),ds=buildDates(cols.map(x=>x.day),my.month,my.year);cols=cols.map((x,i)=>({c:x.c,date:ds[i]}))}else cols=cols.filter(x=>x.date);let blanks=0;for(let r=Math.max(ch.g.nameRow,ch.g.cargoRow)+1;r<ch.rows.length;r++){const row=ch.rows[r]||[],name=cellText(row[ch.g.nameCol]);if(!name){if(++blanks>14)break;continue}blanks=0;const key=norm(name);if(!key||/^(TOTAL|LEGENDA|GERENCIAL|CONSOLIDADO|MOTOR DE LANCAMENTOS)$/.test(key))continue;const days=[];for(const d of cols){const code=norm(cellText(row[d.c]));if(CODE.test(code))days.push({date:d.date,code})}if(days.length<5)continue;const emp={name:name.trim(),key,cargo:norm(cellText(row[ch.g.cargoCol]))||'NÃO IDENTIFICADO',days:new Map()};for(const x of days){const t=out.turns.get(x.code);emp.days.set(x.date,{date:x.date,code:x.code,start:t?.start||null});out.quality.codeCells++}mergeEmployee(out.employees,emp);out.quality.rows++}if(!out.store)throw new Error('Escala Excel: loja não reconhecida.');if(!out.employees.size)throw new Error('Escala Excel: colaboradores não reconhecidos.');const ds=[...out.employees.values()].flatMap(e=>[...e.days.keys()]).filter(Boolean).sort();out.periodStart=ds[0]||null;out.periodEnd=ds.at(-1)||null;return out}
function lev(a,b){const m=a.length,n=b.length,d=Array.from({length:m+1},(_,i)=>[i]);for(let j=1;j<=n;j++)d[0][j]=j;for(let i=1;i<=m;i++)for(let j=1;j<=n;j++)d[i][j]=Math.min(d[i-1][j]+1,d[i][j-1]+1,d[i-1][j-1]+(a[i-1]===b[j-1]?0:1));return d[m][n]}
function sim(a,b){return 1-lev(a,b)/Math.max(1,a.length,b.length)}
function tokenSim(a,b){const A=new Set(a.split(' ').filter(Boolean)),B=new Set(b.split(' ').filter(Boolean)),u=new Set([...A,...B]).size||1;return[...A].filter(x=>B.has(x)).length/u}
function matchEmp(s,points,used){if(points.has(s.key)&&!used.has(s.key))return{emp:points.get(s.key),key:s.key,mode:'exato',confidence:1};const pref=[];for(const[k,p]of points){if(used.has(k))continue;const len=Math.min(k.length,s.key.length);if(len>=12&&(k.startsWith(s.key)||s.key.startsWith(k)))pref.push({emp:p,key:k,mode:'truncado',confidence:len/Math.max(k.length,s.key.length)})}if(pref.length===1)return pref[0];const a=[];for(const[k,p]of points){if(used.has(k))continue;const ts=tokenSim(s.key,k),sameFirst=s.key.split(' ')[0]===k.split(' ')[0],sc=sim(s.key,k)*.7+ts*.3;if(sameFirst&&ts>=.75)a.push({emp:p,key:k,mode:'aproximado',confidence:sc})}a.sort((x,y)=>y.confidence-x.confidence);return a[0]&&a[0].confidence>=.97&&(!a[1]||a[0].confidence-a[1].confidence>=.07)?a[0]:null}
function pointMarks(p,s,e){let n=0;for(const emp of p.employees.values())for(const[d,x]of emp.days)if(d>=s&&d<=e)n+=x.marks.length;return n}
function employeeMarks(emp,s,e){let n=0;for(const[d,x]of emp.days)if(d>=s&&d<=e)n+=x.marks.length;return n}
function analyze(point,schedule){if(point.store!==schedule.store)throw new Error(`Lojas diferentes: ${point.store} × ${schedule.store}.`);const start=point.periodStart,end=point.periodEnd;if(!schedule.periodStart||!schedule.periodEnd||schedule.periodStart>start||schedule.periodEnd<end)throw new Error(`A escala não cobre ${fmtDate(start)} a ${fmtDate(end)}.`);const used=new Set(),pairs=[],unmatchedSchedule=[];let trunc=0,approx=0;for(const s of schedule.employees.values()){const m=matchEmp(s,point.employees,used);if(!m){unmatchedSchedule.push(s.name);continue}used.add(m.key);if(m.mode==='truncado')trunc++;if(m.mode==='aproximado')approx++;pairs.push({schedule:s,point:m.emp,mode:m.mode})}
const cargoStats=new Map(),usedTurns=new Set();let dev=0,nc=0,total=0,unresolvedDays=0,unresolvedMarks=0,missingScheduleMarks=0,unknownCodeMarks=0,flexMarks=0,matchedWithMarks=0;for(const pair of pairs){const p=pair.point,s=pair.schedule,hasMarks=employeeMarks(p,start,end)>0;if(hasMarks)matchedWithMarks++;const cargo=p.cargo!=='NÃO IDENTIFICADO'?p.cargo:s.cargo;if(!cargoStats.has(cargo))cargoStats.set(cargo,{days:0,deviations:0,nc:0});const cs=cargoStats.get(cargo);for(const[date,pd]of p.days){if(date<start||date>end||!pd.marks.length)continue;const sd=s.days.get(date);if(!sd){missingScheduleMarks+=pd.marks.length;continue}cs.days++;if(NONWORK.has(sd.code)){nc++;cs.nc++;total+=pd.marks.length;continue}if(FLEX.has(sd.code)){total+=pd.marks.length;flexMarks+=pd.marks.length;continue}if(/^T\d{1,2}$/.test(sd.code)){usedTurns.add(sd.code);if(!sd.start){unresolvedDays++;unresolvedMarks+=pd.marks.length;continue}total+=pd.marks.length;if(pd.firstEntry&&timeDiff(sd.start,pd.firstEntry)>90){dev++;cs.deviations++}continue}unknownCodeMarks+=pd.marks.length}}
const all=pointMarks(point,start,end),pointOnly=[...point.employees.entries()].filter(([k])=>!used.has(k)).map(([,e])=>({name:e.name,marks:employeeMarks(e,start,end)})).filter(x=>x.marks>0),pointOnlyMarks=pointOnly.reduce((n,x)=>n+x.marks,0),people=[...point.employees.values()].filter(e=>employeeMarks(e,start,end)>0).length,coverage=all?total/all:0,nameCov=people?Math.min(1,matchedWithMarks/people):1,turnCov=usedTurns.size?[...usedTurns].filter(t=>schedule.turns.has(t)).length/usedTurns.size:1,parseQ=schedule.source==='excel'?(schedule.quality.realDates>=300?1:.97):(schedule.quality.source==='text'?1:.90),confidence=Math.max(0,Math.min(100,100*(.40*coverage+.25*nameCov+.20*turnCov+.15*parseQ)-approx*1.5));const exclusions={pointOnlyMarks,missingScheduleMarks,unresolvedMarks,unknownCodeMarks};if(unresolvedDays)throw new Error(`${unresolvedDays} dia(s) com marcação usam turno sem horário reconhecido (${unresolvedMarks} marcações).`);if(!total)throw new Error('Nenhuma marcação utilizável foi encontrada após o cruzamento.');if(coverage<.98){const parts=[];if(pointOnlyMarks)parts.push(`${pointOnlyMarks} de colaborador(es) sem conciliação`);if(missingScheduleMarks)parts.push(`${missingScheduleMarks} sem célula de escala para a data`);if(unknownCodeMarks)parts.push(`${unknownCodeMarks} em código sem regra de comparação`);throw new Error(`Cobertura ${pct(coverage)} abaixo de 98%. ${all-total} de ${all} marcações ficaram fora da análise${parts.length?`: ${parts.join('; ')}`:''}.`)}if(confidence<92)throw new Error(`Confiabilidade ${pct(confidence/100)} insuficiente. Cobertura ${pct(coverage)}; conciliação de nomes ${pct(nameCov)}.`);const raw=1-(dev+10*nc)/total,adherence=Math.max(0,Math.min(1,raw));return{store:point.store,periodStart:start,periodEnd:end,adherence,rawAdherence:raw,confidence:confidence/100,coverage,deviations:dev,nonConformities:nc,totalMarks:total,totalPointMarks:all,matched:matchedWithMarks,pointPeople:people,turnsUsed:[...usedTurns],turnsRecognized:schedule.turns.size,pointOnly,unmatchedSchedule,cargoStats:[...cargoStats.entries()].map(([cargo,v])=>({cargo,...v})),source:schedule.source,truncatedMatches:trunc,approxMatches:approx,flexMarks,exclusions,pointStoreCandidates:point.quality.storeCandidates||[]}}
async function parsePointFile(file){return parsePointPages(await pdfTextPages(file),file?.name||'')}
async function parseScheduleFile(file,opts={}){const n=file.name.toLowerCase();if(n.endsWith('.pdf'))return parseSchedulePdf(await schedulePdfPages(file,opts.onProgress));if(/\.(xlsx|xlsm|xls)$/.test(n))return parseScheduleWorkbook(await file.arrayBuffer());throw new Error('Formato não suportado. Use PDF, XLSX, XLSM ou XLS.')}
window.ADERENCIA_ENGINE={parsePointFile,parseScheduleFile,analyze,fmtDate,pct,pointMarks};
// Integração com a análise individual
const pointInput=$('pointFile'),scheduleInput=$('scheduleFile'),calcBtn=$('calculateBtn'),resetBtn=$('resetBtn');let pointData=null,scheduleData=null;
function setStatus(id,text,state='muted'){const e=$(id);if(!e)return;e.textContent=text;e.classList.remove('muted','ok','error');e.classList.add(state)}
function enable(){if(calcBtn)calcBtn.disabled=!(pointData&&scheduleData)}
function renderConfidence(v,final=true){v=Math.max(0,Math.min(100,v));$('analysisArea')?.classList.remove('hidden');if($('confidencePercent'))$('confidencePercent').textContent=`${v.toFixed(final?1:0).replace('.',',')}%`;if($('confidenceBar'))$('confidenceBar').style.width=`${v}%`;const b=$('confidenceBadge');if(b){b.className='confidence-badge '+(v>=97?'high':v>=90?'medium':'low');b.textContent=v>=97?'Muito alta':v>=90?'Alta':'Revisar'}}
function sourceLabel(s){return s==='excel'?'Excel/XLSM':s==='pdf-ocr'?'PDF + OCR':'PDF com texto'}
function renderPre(){if(!pointData&&!scheduleData)return;$('analysisArea')?.classList.remove('hidden');$('resultCard')?.classList.add('hidden');let q=0;if(pointData?.store)q+=10;if(pointData?.periodStart)q+=10;if(scheduleData?.store)q+=10;if(scheduleData?.periodStart)q+=10;if(scheduleData?.turns?.size>=29)q+=20;if(scheduleData?.employees?.size)q+=20;if(pointData&&scheduleData&&pointData.store===scheduleData.store)q+=10;if(pointData&&scheduleData&&scheduleData.periodStart<=pointData.periodStart&&scheduleData.periodEnd>=pointData.periodEnd)q+=10;renderConfidence(q,false);if($('metaSource'))$('metaSource').textContent=scheduleData?sourceLabel(scheduleData.source):'—';if($('metaStore'))$('metaStore').textContent=scheduleData?.store||pointData?.store||'—';if($('metaPeriod'))$('metaPeriod').textContent=pointData?`${fmtDate(pointData.periodStart)} a ${fmtDate(pointData.periodEnd)}`:'—';if($('metaTurns'))$('metaTurns').textContent=scheduleData?String(scheduleData.turns.size):'—';if($('metaPointMarks'))$('metaPointMarks').textContent=pointData?String(pointMarks(pointData,pointData.periodStart,pointData.periodEnd)):'—';if($('metaCoverage'))$('metaCoverage').textContent='—'}
function renderResult(a){window.ADERENCIA_LAST_ANALYSIS=a;renderConfidence(a.confidence*100,true);$('metaSource').textContent=sourceLabel(a.source);$('metaStore').textContent=a.store;$('metaPeriod').textContent=`${fmtDate(a.periodStart)} a ${fmtDate(a.periodEnd)}`;$('metaTurns').textContent=`${a.turnsRecognized} (${a.turnsUsed.length} usados)`;$('metaPointMarks').textContent=a.totalPointMarks;$('metaCoverage').textContent=pct(a.coverage);$('causeSummary').innerHTML=[`<div class="cause-item ${a.deviations?'attention':''}"><strong>${a.deviations} desvios acima de 90 min</strong><span>Entrada fora da tolerância.</span></div>`,`<div class="cause-item ${a.nonConformities?'critical':''}"><strong>${a.nonConformities} folgas/ausências com marcação</strong><span>1 ocorrência por colaborador/data.</span></div>`,a.pointOnly.length?`<div class="cause-item attention"><strong>${a.pointOnly.length} pessoa(s) apenas no ponto</strong><span>${a.exclusions.pointOnlyMarks} marcação(ões) fora do cruzamento.</span></div>`:'',a.unmatchedSchedule.length?`<div class="cause-item"><strong>${a.unmatchedSchedule.length} pessoa(s) apenas na escala</strong><span>Sem correspondência no espelho.</span></div>`,a.flexMarks?`<div class="cause-item"><strong>${a.flexMarks} marcação(ões) em código D</strong><span>Contabilizadas na cobertura sem penalidade horária.</span></div>`:''].join('');const cr=a.cargoStats.map(x=>({...x,occ:x.deviations+x.nc})).filter(x=>x.occ).sort((x,y)=>y.occ-x.occ||y.days-x.days).slice(0,5);$('cargoSummary').innerHTML=cr.length?cr.map(x=>`<div class="cargo-item"><strong>${x.cargo}</strong><span>${x.occ} ocorrência(s) em ${x.days} dia(s) avaliados • ${x.deviations} desvio(s) • ${x.nc} folga/ausência</span></div>`).join(''):'<p>Nenhuma ocorrência por cargo.</p>';$('resultPercent').textContent=pct(a.adherence,2);$('resultStore').textContent=a.store;$('matchedPeople').textContent=`${a.matched}/${a.pointPeople}`;$('deviations').textContent=a.deviations;$('nonConformities').textContent=a.nonConformities;$('totalMarks').textContent=a.totalMarks;$('warnings').innerHTML=[`<div>Leitura validada • confiabilidade ${pct(a.confidence)} • cobertura ${pct(a.coverage)}.</div>`,a.truncatedMatches?`<div>${a.truncatedMatches} nome(s) truncado(s) conciliados por prefixo único.</div>`:'',a.approxMatches?`<div>${a.approxMatches} nome(s) conciliado(s) por similaridade controlada.</div>`:'',a.pointStoreCandidates.length>1?`<div>Referências de outras ML foram ignoradas; loja principal identificada como ${a.store}.</div>`:''].join('');$('resultCard').classList.remove('hidden')}
async function onPoint(file){pointData=null;window.ADERENCIA_LAST_ANALYSIS=null;$('resultCard')?.classList.add('hidden');$('pointFileName').textContent=file?.name||'Nenhum arquivo selecionado';if(!file){setStatus('pointStatus','Aguardando arquivo');enable();return}try{setStatus('pointStatus','Lendo espelho...');pointData=await parsePointFile(file);setStatus('pointStatus',`Reconhecido: ${pointData.employees.size} funcionário(s) • ${pointData.store} • ${pointMarks(pointData,pointData.periodStart,pointData.periodEnd)} marcações`,'ok');renderPre()}catch(e){setStatus('pointStatus',`Erro: ${e.message}`,'error');if(!window.ADERENCIA_BATCH_MODE)alert(e.message)}enable()}
async function onSchedule(file){scheduleData=null;window.ADERENCIA_LAST_ANALYSIS=null;$('resultCard')?.classList.add('hidden');$('scheduleFileName').textContent=file?.name||'Nenhum arquivo selecionado';if(!file){setStatus('scheduleStatus','Aguardando arquivo');enable();return}try{setStatus('scheduleStatus','Lendo escala...');scheduleData=await parseScheduleFile(file,{onProgress:t=>setStatus('scheduleStatus',t)});setStatus('scheduleStatus',`Reconhecida: ${scheduleData.employees.size} funcionário(s) • ${scheduleData.store} • ${scheduleData.turns.size} turnos • ${fmtDate(scheduleData.periodStart)} a ${fmtDate(scheduleData.periodEnd)}`,'ok');renderPre()}catch(e){setStatus('scheduleStatus',`Erro: ${e.message}`,'error');if(!window.ADERENCIA_BATCH_MODE)alert(e.message)}enable()}
pointInput?.addEventListener('change',()=>onPoint(pointInput.files?.[0]));scheduleInput?.addEventListener('change',()=>onSchedule(scheduleInput.files?.[0]));calcBtn?.addEventListener('click',e=>{e.preventDefault();try{window.ADERENCIA_LAST_ERROR=null;const a=analyze(pointData,scheduleData);renderResult(a)}catch(err){window.ADERENCIA_LAST_ANALYSIS=null;window.ADERENCIA_LAST_ERROR=err.message;$('resultCard')?.classList.add('hidden');if(!window.ADERENCIA_BATCH_MODE)alert(err.message)}});resetBtn?.addEventListener('click',()=>{pointInput.value='';scheduleInput.value='';pointData=null;scheduleData=null;window.ADERENCIA_LAST_ANALYSIS=null;window.ADERENCIA_LAST_ERROR=null;$('pointFileName').textContent='Nenhum arquivo selecionado';$('scheduleFileName').textContent='Nenhum arquivo selecionado';setStatus('pointStatus','Aguardando arquivo');setStatus('scheduleStatus','Aguardando arquivo');$('analysisArea')?.classList.add('hidden');enable()});enable();
})();