(function(){
'use strict';
const $=id=>document.getElementById(id),btn=$('exportPdfBtn'),result=$('resultCard');if(!btn||!result)return;
const clean=v=>String(v??'').replace(/\s+/g,' ').trim(),value=id=>clean($(id)?.textContent||'—'),num=v=>{const m=String(v).match(/-?\d+(?:[.,]\d+)?/);return m?Number(m[0].replace(',','.')):0},safe=v=>clean(v).replace(/[^A-Za-z0-9_-]+/g,'_').replace(/^_+|_+$/g,'');
function ready(){return !result.classList.contains('hidden')&&value('resultPercent')!=='—'}function sync(){btn.disabled=!ready()}new MutationObserver(sync).observe(result,{attributes:true});sync();
function cargoData(){const structured=window.ADERENCIA_LAST_ANALYSIS?.cargoStats;if(Array.isArray(structured)&&structured.length)return structured.map(x=>({title:x.cargo,occ:(x.deviations||0)+(x.nc||0),days:x.days||0,rate:x.days?((x.deviations||0)+(x.nc||0))/x.days*100:0,detail:`${(x.deviations||0)+(x.nc||0)} ocorrência(s) em ${x.days||0} dia(s) avaliados • ${x.deviations||0} desvio(s) • ${x.nc||0} folga/ausência`})).filter(x=>x.occ>0).sort((a,b)=>b.rate-a.rate||b.occ-a.occ);return[...document.querySelectorAll('#cargoSummary .cargo-item')].map(el=>{const title=clean(el.querySelector('strong')?.textContent),detail=clean(el.querySelector('span')?.textContent),m=detail.match(/(\d+)\s+ocorr.*?em\s+(\d+)\s+dia/i),occ=m?+m[1]:num(detail),days=m?+m[2]:0;return{title,detail,occ,days,rate:days?occ/days*100:0}}).filter(x=>x.title&&x.occ>0).sort((a,b)=>b.rate-a.rate||b.occ-a.occ)}
function collect(){const causes=[...document.querySelectorAll('#causeSummary .cause-item')].map(el=>({title:clean(el.querySelector('strong')?.textContent),detail:clean(el.querySelector('span')?.textContent)})).filter(x=>x.title);return{store:value('resultStore')||value('metaStore'),period:value('metaPeriod'),source:value('metaSource'),turns:value('metaTurns'),pointMarks:value('metaPointMarks'),coverage:value('metaCoverage'),adherence:value('resultPercent'),confidence:value('confidencePercent'),matched:value('matchedPeople'),deviations:value('deviations'),nc:value('nonConformities'),considered:value('totalMarks'),causes,cargos:cargoData()}}
function exportPdf(){if(!ready())return;if(!window.jspdf?.jsPDF){alert('Gerador de PDF não carregado.');return}const d=collect(),{jsPDF}=window.jspdf,doc=new jsPDF({orientation:'landscape',unit:'mm',format:'a4',compress:true}),W=297,H=210,M=12;
const C={navy:[19,31,44],navy2:[31,48,66],ink:[35,48,65],muted:[104,119,137],line:[224,231,237],soft:[247,249,251],white:[255,255,255],green:[28,128,82],amber:[190,124,8],red:[183,72,61],blue:[76,111,143]};
const fill=c=>doc.setFillColor(...c),stroke=c=>doc.setDrawColor(...c);function font(s,st='normal',c=C.ink){doc.setFont('helvetica',st);doc.setFontSize(s);doc.setTextColor(...c)}function text(t,x,y,o={}){doc.text(String(t),x,y,o)}function box(x,y,w,h,fc=C.white,rc=C.line,r=3){fill(fc);stroke(rc);doc.setLineWidth(.25);doc.roundedRect(x,y,w,h,r,r,'FD')}function wrap(t,w){return doc.splitTextToSize(clean(t),w)}function progress(x,y,w,h,p,fore){fill(C.soft);doc.roundedRect(x,y,w,h,h/2,h/2,'F');fill(fore);doc.roundedRect(x,y,Math.max(h,Math.min(w,w*p)),h,h/2,h/2,'F')}function kpi(x,y,w,label,val,accent){box(x,y,w,20);fill(accent);doc.roundedRect(x,y,2.3,20,1.1,1.1,'F');font(5.7,'bold',C.muted);text(label.toUpperCase(),x+6,y+6);font(14,'bold',C.ink);text(val,x+6,y+15)}
const adh=num(d.adherence),status=adh>=90?'ADEQUADO':adh>=80?'ATENÇÃO':'CRÍTICO',statusColor=adh>=90?C.green:adh>=80?C.amber:C.red,delta=Math.abs(adh-90).toFixed(2).replace('.',',');
fill(C.navy);doc.rect(0,0,W,30,'F');font(7,'bold',[173,193,211]);text('RELATÓRIO EXECUTIVO DE ADERÊNCIA DE ESCALA',M,8);font(27,'bold',C.white);text(d.store||'LOJA',M,21);font(8,'normal',[215,225,234]);text(`${d.period}  •  ${d.source}`,M+48,20.5);font(6,'normal',[184,201,215]);text(`Gerado em ${new Date().toLocaleString('pt-BR')}`,W-M,8,{align:'right'});
const top=36;box(M,top,82,58,C.navy2,C.navy2,4);font(6.5,'bold',[181,198,214]);text('ADERÊNCIA DO PERÍODO',M+7,top+9);font(35,'bold',C.white);text(d.adherence,M+7,top+29);progress(M+7,top+36,68,5,Math.max(0,Math.min(1,adh/100)),statusColor);font(7,'bold',statusColor);text(status,M+7,top+49);font(6,'normal',[205,216,226]);text(`${delta} p.p. ${adh>=90?'acima':'abaixo'} da referência de 90%`,M+27,top+49);
const x=M+87;kpi(x,top,38,'Desvios > 90 min',d.deviations,C.amber);kpi(x+41,top,38,'Dias-pessoa em folga',d.nc,C.red);kpi(x+82,top,38,'Colaboradores',d.matched,C.blue);kpi(x+123,top,38,'Marcações',d.considered,C.navy);box(x,top+24,161,34,C.soft,C.line,3);font(6.3,'bold',C.ink);text('VALIDAÇÃO DA LEITURA',x+6,top+31);font(12,'bold',C.green);text(d.confidence,x+6,top+43);font(5.8,'normal',C.muted);text('confiabilidade',x+6,top+49);font(6,'normal',C.muted);text('Cobertura',x+48,top+37);font(7,'bold',C.ink);text(d.coverage,x+48,top+44);font(6,'normal',C.muted);text('Turnos',x+82,top+37);font(7,'bold',C.ink);text(d.turns,x+82,top+44);font(6,'normal',C.muted);text('Marcações no espelho',x+112,top+37);font(7,'bold',C.ink);text(d.pointMarks,x+112,top+44);
const y=101,gap=6,cw=(W-2*M-2*gap)/3;box(M,y,cw,78);font(8.2,'bold');text('Resumo das ocorrências',M+6,y+9);const causes=[{label:'Entradas fora da tolerância > 90 min',v:num(d.deviations),c:C.amber},{label:'Dias-pessoa com ponto em folga/ausência',v:num(d.nc),c:C.red}];const op=d.causes.find(c=>/apenas no ponto/i.test(c.title));if(op)causes.push({label:'Pessoas somente no ponto',v:num(op.title),c:C.blue});const mx=Math.max(1,...causes.map(r=>r.v));let cy=y+19;causes.forEach(r=>{font(6.2,'bold');text(r.label,M+6,cy);font(7,'bold',r.c);text(String(r.v),M+cw-7,cy,{align:'right'});progress(M+6,cy+3,cw-13,4,r.v/mx,r.c);cy+=17});font(5.5,'normal',C.muted);doc.text(wrap('Dias-pessoa: 1 ocorrência por colaborador/data quando há ao menos uma batida em F, FER, AF, AB, AL, FF, FC, NC ou AE.',cw-12),M+6,y+69,{lineHeightFactor:1.2});
const x2=M+cw+gap;box(x2,y,cw,78);font(8.2,'bold');text('Incidência por cargo',x2+6,y+9);font(5.5,'normal',C.muted);text('Ocorrências / dias avaliados',x2+6,y+14);const cargos=d.cargos.slice(0,5),mr=Math.max(1,...cargos.map(c=>c.rate));let yy=y+23;cargos.forEach(c=>{font(5.9,'bold');text(c.title,x2+6,yy);font(6.4,'bold',C.blue);text(`${c.rate.toFixed(1).replace('.',',')}%`,x2+cw-7,yy,{align:'right'});progress(x2+6,yy+2.5,cw-13,3,c.rate/mr,C.blue);font(4.9,'normal',C.muted);text(`${c.occ} ocorrência(s) em ${c.days||'—'} dia(s) avaliados`,x2+6,yy+8);yy+=11});if(!cargos.length){font(6,'normal',C.muted);text('Nenhuma ocorrência registrada por cargo.',x2+6,y+25)}
const x3=x2+cw+gap;box(x3,y,cw,78);font(8.2,'bold');text('Leitura executiva',x3+6,y+9);const refs=[{n:d.adherence,t:`aderência • ${status.toLowerCase()}`,c:statusColor},{n:d.deviations,t:'entradas fora da tolerância',c:C.amber},{n:d.nc,t:'dias-pessoa com ponto em folga/ausência',c:C.red},{n:d.coverage,t:'cobertura efetiva das marcações',c:C.green},{n:d.confidence,t:'confiabilidade da leitura',c:C.blue}];let ry=y+19;refs.forEach(r=>{fill(C.soft);doc.roundedRect(x3+6,ry-6,cw-12,10,2,2,'F');font(10,'bold',r.c);text(r.n,x3+9,ry);font(5.7,'normal',C.ink);text(r.t,x3+30,ry);ry+=11.5});
stroke(C.line);doc.line(M,185,W-M,185);font(5.6,'bold');text('METODOLOGIA',M,191);font(5.3,'normal',C.muted);doc.text(wrap('Primeira entrada real × entrada prevista. Até 90 min: tolerado. >90 min: 1 ponto. Ponto em folga/ausência: 10 pontos por colaborador/data.',178),M+24,191,{lineHeightFactor:1.15});font(5.3,'bold',C.navy);text('Aderência = 1 - (desvios + 10 × não conformidades) / total de marcações',W-M,191,{align:'right'});font(5,'normal',C.muted);text('Motor de Aderência • processamento local no navegador',M,H-7);text('Relatório executivo • 1 página',W-M,H-7,{align:'right'});doc.save(`Relatorio_Aderencia_${safe(d.store)}_${safe(d.period.replace(/\//g,''))}.pdf`)}
btn.addEventListener('click',function(){const old=btn.textContent;try{btn.disabled=true;btn.textContent='Gerando PDF...';exportPdf()}catch(e){console.error(e);alert(`Não foi possível gerar o relatório: ${e.message}`)}finally{btn.textContent=old;sync()}});
})();