(function(){
'use strict';
const $=id=>document.getElementById(id);
function ready(){return !!window.jspdf?.jsPDF&&!!window.ADERENCIA_HISTORY}
const H=()=>window.ADERENCIA_HISTORY;
const val=id=>$(id)?.value;
function periodLabel(month,year){const m=month==='all'?'Todos os meses':H().months[+month-1];return year==='all'?m:`${m} • ${year}`}
function header(doc,title,subtitle){doc.setFillColor(19,31,44);doc.rect(0,0,297,28,'F');doc.setTextColor(255,255,255);doc.setFont('helvetica','bold');doc.setFontSize(20);doc.text(title,12,17);doc.setFont('helvetica','normal');doc.setFontSize(8);doc.setTextColor(210,220,230);doc.text(subtitle,285,17,{align:'right'});doc.setTextColor(35,48,65)}
function footer(doc){doc.setDrawColor(225,232,238);doc.line(12,198,285,198);doc.setFontSize(6);doc.setTextColor(112,126,142);doc.text('Central de Aderência • dados armazenados localmente',12,203);doc.text(`Gerado em ${new Date().toLocaleString('pt-BR')}`,285,203,{align:'right'})}
function card(doc,x,y,w,h,label,value,accent=[76,111,143]){doc.setFillColor(255,255,255);doc.setDrawColor(224,231,237);doc.roundedRect(x,y,w,h,3,3,'FD');doc.setFillColor(...accent);doc.roundedRect(x,y,2.4,h,1.2,1.2,'F');doc.setFont('helvetica','bold');doc.setFontSize(6);doc.setTextColor(112,126,142);doc.text(label.toUpperCase(),x+6,y+7);doc.setFontSize(16);doc.setTextColor(35,48,65);doc.text(String(value),x+6,y+19)}
function exportHistory(){if(!ready())return alert('Gerador de PDF indisponível.');const {jsPDF}=window.jspdf,doc=new jsPDF({orientation:'landscape',unit:'mm',format:'a4'}),m=val('historyMonth'),y=val('historyYear'),s=val('historyStore'),rows=H().load().filter(r=>(m==='all'||r.month===+m)&&(y==='all'||r.year===+y)&&(s==='all'||r.store===s));const map=new Map();rows.forEach(r=>{if(!map.has(r.store))map.set(r.store,[]);map.get(r.store).push(H().effective(r))});const list=[...map].map(([store,a])=>({store,value:a.reduce((x,z)=>x+z,0)/a.length})).sort((a,b)=>b.value-a.value),avg=list.length?list.reduce((x,z)=>x+z.value,0)/list.length:null;header(doc,'Histórico de Aderência',`${periodLabel(m,y)} • ${s==='all'?'Todas as lojas':s}`);card(doc,12,36,62,26,'Lojas com resultado',list.length);card(doc,79,36,62,26,'Média',H().fmt(avg),[31,138,92]);card(doc,146,36,62,26,'≥ 95%',list.filter(x=>x.value>=95).length,[31,138,92]);card(doc,213,36,72,26,'< 80%',list.filter(x=>x.value<80).length,[185,72,61]);doc.setFont('helvetica','bold');doc.setFontSize(10);doc.text('Aderência por loja',12,73);let yy=80;const maxRows=24;list.slice(0,maxRows).forEach((r,i)=>{const c=H().light(r.value),color=c==='green'?[31,138,92]:c==='yellow'?[209,138,10]:[185,72,61];doc.setFontSize(7);doc.setTextColor(35,48,65);doc.text(`${r.store} - ${H().stores[r.store]}`,12,yy);doc.setFillColor(238,242,245);doc.roundedRect(78,yy-3.5,170,4,2,2,'F');doc.setFillColor(...color);doc.roundedRect(78,yy-3.5,170*(r.value/100),4,2,2,'F');doc.setFont('helvetica','bold');doc.text(H().fmt(r.value),282,yy,{align:'right'});doc.setFont('helvetica','normal');yy+=4.6});if(list.length>maxRows){doc.setFontSize(6.5);doc.setTextColor(112,126,142);doc.text(`+ ${list.length-maxRows} loja(s) não exibidas por limite visual desta página.`,12,193)}footer(doc);doc.save(`Historico_Aderencia_${String(m)}_${String(y)}.pdf`)}
function exportMonitor(){if(!ready())return;const {jsPDF}=window.jspdf,doc=new jsPDF({orientation:'landscape',unit:'mm',format:'a4'}),m=+val('monitorMonth'),y=+val('monitorYear'),by=new Map(H().load().filter(r=>r.month===m&&r.year===y).map(r=>[r.store,r]));header(doc,'Painel de Monitoramento',`${H().months[m-1]} • ${y}`);let x=12,yy=38,col=0,row=0;Object.keys(H().stores).forEach((store,i)=>{const r=by.get(store),v=r?H().effective(r):NaN,l=H().light(v),c=l==='green'?[31,138,92]:l==='yellow'?[209,138,10]:l==='red'?[185,72,61]:[170,180,190];const w=43,h=19;x=12+col*45.5;yy=38+row*21.5;doc.setFillColor(255,255,255);doc.setDrawColor(224,231,237);doc.roundedRect(x,yy,w,h,2.5,2.5,'FD');doc.setFillColor(...c);doc.circle(x+5,yy+6,2,'F');doc.setFont('helvetica','bold');doc.setFontSize(7.5);doc.setTextColor(35,48,65);doc.text(store,x+9,yy+7);doc.setFontSize(10);doc.text(Number.isFinite(v)?H().fmt(v):'—',x+w-4,yy+7,{align:'right'});doc.setFont('helvetica','normal');doc.setFontSize(5.4);doc.setTextColor(112,126,142);const name=doc.splitTextToSize(H().stores[store],w-8)[0];doc.text(name,x+4,yy+14);col++;if(col===6){col=0;row++}});footer(doc);doc.save(`Monitoramento_${String(m).padStart(2,'0')}_${y}.pdf`)}
function exportSemester(){if(!ready())return;const {jsPDF}=window.jspdf,doc=new jsPDF({orientation:'landscape',unit:'mm',format:'a4'}),y=+val('semesterYear'),s=val('semesterStore'),all=H().load().filter(r=>r.year===y&&(s==='all'||r.store===s));const avg=(rows,months)=>{const a=rows.filter(r=>months.includes(r.month)).map(H().effective);return a.length?a.reduce((x,z)=>x+z,0)/a.length:null};header(doc,'Comparativo Semestral',`${y} • ${s==='all'?'Todas as lojas':s}`);const a=avg(all,[1,2,3,4,5,6]),b=avg(all,[7,8,9,10,11,12]),d=Number.isFinite(a)&&Number.isFinite(b)?b-a:null;card(doc,12,36,82,26,'1º semestre',H().fmt(a),[76,111,143]);card(doc,107,36,82,26,'2º semestre',H().fmt(b),[31,138,92]);card(doc,202,36,83,26,'Variação',Number.isFinite(d)?`${d>=0?'+':''}${d.toFixed(2).replace('.',',')} p.p.`:'—',d>=0?[31,138,92]:[185,72,61]);doc.setFont('helvetica','bold');doc.setFontSize(10);doc.text('Comparativo por loja',12,74);const stores=s==='all'?Object.keys(H().stores):[s];let yy=82;doc.setFontSize(6.5);doc.setTextColor(112,126,142);doc.text('LOJA',12,yy);doc.text('1º SEM.',205,yy,{align:'right'});doc.text('2º SEM.',245,yy,{align:'right'});doc.text('VARIAÇÃO',282,yy,{align:'right'});yy+=5;stores.slice(0,25).forEach(st=>{const r=all.filter(x=>x.store===st),x=avg(r,[1,2,3,4,5,6]),z=avg(r,[7,8,9,10,11,12]),dd=Number.isFinite(x)&&Number.isFinite(z)?z-x:null;doc.setDrawColor(238,242,245);doc.line(12,yy+1,285,yy+1);doc.setFont('helvetica','normal');doc.setFontSize(7);doc.setTextColor(35,48,65);doc.text(`${st} - ${H().stores[st]}`,12,yy);doc.setFont('helvetica','bold');doc.text(H().fmt(x),205,yy,{align:'right'});doc.text(H().fmt(z),245,yy,{align:'right'});doc.text(Number.isFinite(dd)?`${dd>=0?'+':''}${dd.toFixed(2).replace('.',',')} p.p.`:'—',282,yy,{align:'right'});yy+=4.4});footer(doc);doc.save(`Semestral_${y}_${s}.pdf`)}
$('historyPdfBtn')?.addEventListener('click',exportHistory);$('monitorPdfBtn')?.addEventListener('click',exportMonitor);$('semesterPdfBtn')?.addEventListener('click',exportSemester);
})();