(function(){
'use strict';
const $=id=>document.getElementById(id);
const H=()=>window.ADERENCIA_HISTORY;
const val=id=>$(id)?.value;
function ready(){return !!window.jspdf?.jsPDF&&!!H()}
function periodLabel(month,year){const m=month==='all'?'Todos os meses':H().months[+month-1];return year==='all'?m:`${m} • ${year}`}
function header(doc,title,subtitle){doc.setFillColor(19,31,44);doc.rect(0,0,297,28,'F');doc.setTextColor(255,255,255);doc.setFont('helvetica','bold');doc.setFontSize(20);doc.text(title,12,17);doc.setFont('helvetica','normal');doc.setFontSize(8);doc.setTextColor(210,220,230);doc.text(subtitle,285,17,{align:'right'});doc.setTextColor(35,48,65)}
function footer(doc,page,total){doc.setDrawColor(225,232,238);doc.line(12,198,285,198);doc.setFontSize(6);doc.setTextColor(112,126,142);doc.text('Central de Aderência • dados armazenados localmente',12,203);doc.text(`Página ${page}/${total} • Gerado em ${new Date().toLocaleString('pt-BR')}`,285,203,{align:'right'})}
function card(doc,x,y,w,h,label,value,accent=[76,111,143]){doc.setFillColor(255,255,255);doc.setDrawColor(224,231,237);doc.roundedRect(x,y,w,h,3,3,'FD');doc.setFillColor(...accent);doc.roundedRect(x,y,2.4,h,1.2,1.2,'F');doc.setFont('helvetica','bold');doc.setFontSize(6);doc.setTextColor(112,126,142);doc.text(label.toUpperCase(),x+6,y+7);doc.setFontSize(16);doc.setTextColor(35,48,65);doc.text(String(value),x+6,y+19)}
function colorFor(v){const c=H().light(v);return c==='green'?[31,138,92]:c==='yellow'?[209,138,10]:c==='red'?[185,72,61]:[170,180,190]}
function addHistoryPage(doc,list,page,total,subtitle,showSummary){if(page>1)doc.addPage('a4','landscape');header(doc,'Histórico de Aderência',subtitle);let startY=showSummary?73:42;if(showSummary){const avg=list.length?list.reduce((x,z)=>x+z.value,0)/list.length:null;card(doc,12,36,62,26,'Lojas com resultado',list.length);card(doc,79,36,62,26,'Média',H().fmt(avg),[31,138,92]);card(doc,146,36,62,26,'≥ 95%',list.filter(x=>x.value>=95).length,[31,138,92]);card(doc,213,36,72,26,'< 80%',list.filter(x=>x.value<80).length,[185,72,61])}doc.setFont('helvetica','bold');doc.setFontSize(10);doc.setTextColor(35,48,65);doc.text('Aderência por loja',12,startY);let yy=startY+7;const perPage=showSummary?24:31,from=showSummary?0:24+(page-2)*31,to=Math.min(list.length,from+perPage);for(let i=from;i<to;i++){const r=list[i],color=colorFor(r.value);doc.setFont('helvetica','normal');doc.setFontSize(7);doc.setTextColor(35,48,65);doc.text(`${r.store} - ${H().stores[r.store]}`,12,yy);doc.setFillColor(238,242,245);doc.roundedRect(78,yy-3.5,170,4,2,2,'F');doc.setFillColor(...color);doc.roundedRect(78,yy-3.5,170*(Math.max(0,Math.min(100,r.value))/100),4,2,2,'F');doc.setFont('helvetica','bold');doc.text(H().fmt(r.value),282,yy,{align:'right'});yy+=4.6}footer(doc,page,total)}
function exportHistory(){if(!ready())return alert('Gerador de PDF indisponível.');const {jsPDF}=window.jspdf,m=val('historyMonth'),y=val('historyYear'),s=val('historyStore'),rows=H().load().filter(r=>(m==='all'||r.month===+m)&&(y==='all'||r.year===+y)&&(s==='all'||r.store===s));if(!rows.length)return alert('Não há resultados salvos para os filtros selecionados.');const map=new Map();rows.forEach(r=>{if(!map.has(r.store))map.set(r.store,[]);map.get(r.store).push(H().effective(r))});const list=[...map].map(([store,a])=>({store,value:a.reduce((x,z)=>x+z,0)/a.length})).sort((a,b)=>b.value-a.value),extra=Math.max(0,list.length-24),total=1+(extra?Math.ceil(extra/31):0),doc=new jsPDF({orientation:'landscape',unit:'mm',format:'a4'}),subtitle=`${periodLabel(m,y)} • ${s==='all'?'Todas as lojas':s}`;for(let p=1;p<=total;p++)addHistoryPage(doc,list,p,total,subtitle,p===1);doc.save(`Historico_Aderencia_${String(m)}_${String(y)}.pdf`)}
function exportMonitor(){if(!ready())return alert('Gerador de PDF indisponível.');const {jsPDF}=window.jspdf,m=+val('monitorMonth'),y=+val('monitorYear'),records=H().load().filter(r=>r.month===m&&r.year===y);if(!records.length)return alert('Não há resultados salvos para esta competência.');const doc=new jsPDF({orientation:'landscape',unit:'mm',format:'a4'}),by=new Map(records.map(r=>[r.store,r]));header(doc,'Painel de Monitoramento',`${H().months[m-1]} • ${y}`);const stores=Object.keys(H().stores),cols=8,w=32.4,h=17.5,gx=1.7,gy=2.1,startX=12,startY=38;stores.forEach((store,i)=>{const row=Math.floor(i/cols),col=i%cols,x=startX+col*(w+gx),yy=startY+row*(h+gy),r=by.get(store),v=r?H().effective(r):NaN,c=colorFor(v);doc.setFillColor(255,255,255);doc.setDrawColor(224,231,237);doc.roundedRect(x,yy,w,h,2.3,2.3,'FD');doc.setFillColor(...c);doc.circle(x+4.5,yy+5.2,1.7,'F');doc.setFont('helvetica','bold');doc.setFontSize(6.4);doc.setTextColor(35,48,65);doc.text(store,x+7.5,yy+6);doc.setFontSize(7.8);doc.text(Number.isFinite(v)?H().fmt(v):'—',x+w-3,yy+6,{align:'right'});doc.setFont('helvetica','normal');doc.setFontSize(4.9);doc.setTextColor(112,126,142);doc.text(doc.splitTextToSize(H().stores[store],w-6)[0],x+3,yy+12);if(r?.bonus){doc.setFontSize(4.5);doc.text('★ ajuste +10%',x+3,yy+15.5)}});footer(doc,1,1);doc.save(`Monitoramento_${String(m).padStart(2,'0')}_${y}.pdf`)}
function exportSemester(){if(!ready())return alert('Gerador de PDF indisponível.');const {jsPDF}=window.jspdf,y=+val('semesterYear'),s=val('semesterStore'),all=H().load().filter(r=>r.year===y&&(s==='all'||r.store===s));if(!all.length)return alert('Não há resultados salvos para o filtro semestral selecionado.');const avg=(rows,months)=>{const a=rows.filter(r=>months.includes(r.month)).map(H().effective);return a.length?a.reduce((x,z)=>x+z,0)/a.length:null},a=avg(all,[1,2,3,4,5,6]),b=avg(all,[7,8,9,10,11,12]),d=Number.isFinite(a)&&Number.isFinite(b)?b-a:null,stores=s==='all'?Object.keys(H().stores):[s],perPage=28,total=Math.ceil(stores.length/perPage),doc=new jsPDF({orientation:'landscape',unit:'mm',format:'a4'});for(let p=1;p<=total;p++){if(p>1)doc.addPage('a4','landscape');header(doc,'Comparativo Semestral',`${y} • ${s==='all'?'Todas as lojas':s}`);let tableY=42;if(p===1){card(doc,12,36,82,26,'1º semestre',H().fmt(a),[76,111,143]);card(doc,107,36,82,26,'2º semestre',H().fmt(b),[31,138,92]);card(doc,202,36,83,26,'Variação',Number.isFinite(d)?`${d>=0?'+':''}${d.toFixed(2).replace('.',',')} p.p.`:'—',Number.isFinite(d)&&d>=0?[31,138,92]:[185,72,61]);tableY=74}doc.setFont('helvetica','bold');doc.setFontSize(10);doc.setTextColor(35,48,65);doc.text('Comparativo por loja',12,tableY);let yy=tableY+8;doc.setFontSize(6.5);doc.setTextColor(112,126,142);doc.text('LOJA',12,yy);doc.text('1º SEM.',205,yy,{align:'right'});doc.text('2º SEM.',245,yy,{align:'right'});doc.text('VARIAÇÃO',282,yy,{align:'right'});yy+=5;const from=(p-1)*perPage,to=Math.min(stores.length,from+perPage);for(let i=from;i<to;i++){const st=stores[i],r=all.filter(x=>x.store===st),x=avg(r,[1,2,3,4,5,6]),z=avg(r,[7,8,9,10,11,12]),dd=Number.isFinite(x)&&Number.isFinite(z)?z-x:null;doc.setDrawColor(238,242,245);doc.line(12,yy+1,285,yy+1);doc.setFont('helvetica','normal');doc.setFontSize(7);doc.setTextColor(35,48,65);doc.text(`${st} - ${H().stores[st]}`,12,yy);doc.setFont('helvetica','bold');doc.text(H().fmt(x),205,yy,{align:'right'});doc.text(H().fmt(z),245,yy,{align:'right'});doc.text(Number.isFinite(dd)?`${dd>=0?'+':''}${dd.toFixed(2).replace('.',',')} p.p.`:'—',282,yy,{align:'right'});yy+=4.4}footer(doc,p,total)}doc.save(`Semestral_${y}_${s}.pdf`)}
$('historyPdfBtn')?.addEventListener('click',exportHistory);$('monitorPdfBtn')?.addEventListener('click',exportMonitor);$('semesterPdfBtn')?.addEventListener('click',exportSemester);
})();