(function(){
'use strict';
if(window.__ADERENCIA_PERFORMANCE_RC42__)return;
window.__ADERENCIA_PERFORMANCE_RC42__=true;
const HISTORY_KEY='aderenciaHistoricoV2';
const STORE_KEY='aderenciaStoreRegistryV1';
const metrics={startedAt:performance.now(),historyCacheHits:0,storeCacheHits:0,longTasks:[],lastReadyAt:null};
function installCss(){if(document.getElementById('performanceRc42Styles'))return;const s=document.createElement('style');s.id='performanceRc42Styles';s.textContent='.div-row,.monitor-card,.history-row,.semester-row,.store-list-row{content-visibility:auto;contain-intrinsic-size:1px 74px}.card{contain:layout style paint}.div-table-card,.history-ranking,.history-trend,.evolution-chart-card{contain:layout style}.hidden{content-visibility:hidden!important}';document.head.appendChild(s)}
function wrapHistory(){const H=window.ADERENCIA_HISTORY;if(!H||H.__rc42Cached)return false;H.__rc42Cached=true;const origLoad=H.load.bind(H),origSave=H.saveAll.bind(H);let raw=null,cache=null;H.load=function(){const next=localStorage.getItem(HISTORY_KEY)||'[]';if(cache&&next===raw){metrics.historyCacheHits++;return cache}raw=next;cache=origLoad();return cache};H.saveAll=function(rows){origSave(rows);raw=null;cache=null};window.addEventListener('storage',e=>{if(e.key===HISTORY_KEY){raw=null;cache=null}});window.addEventListener('aderencia:portableloaded',()=>{raw=null;cache=null});return true}
function wrapStores(){const R=window.ADERENCIA_STORE_REGISTRY;if(!R||R.__rc42Cached)return false;R.__rc42Cached=true;const origLoad=R.load.bind(R),origSave=R.save.bind(R),origImport=R.importRegistry?.bind(R);let raw=null,cache=null;R.load=function(){const next=localStorage.getItem(STORE_KEY)||'{}';if(cache&&next===raw){metrics.storeCacheHits++;return cache}raw=next;cache=origLoad();return cache};R.save=function(reg){origSave(reg);raw=null;cache=null};if(origImport)R.importRegistry=function(data){origImport(data);raw=null;cache=null};window.addEventListener('aderencia:storeschange',()=>{raw=null;cache=null});window.addEventListener('aderencia:portableloaded',()=>{raw=null;cache=null});return true}
function installLongTaskObserver(){if(!('PerformanceObserver'in window))return;try{const obs=new PerformanceObserver(list=>{for(const e of list.getEntries()){metrics.longTasks.push({start:+e.startTime.toFixed(1),duration:+e.duration.toFixed(1)});if(metrics.longTasks.length>30)metrics.longTasks.shift()}});obs.observe({entryTypes:['longtask']})}catch{}}
function idle(fn){if('requestIdleCallback'in window)return requestIdleCallback(fn,{timeout:800});return setTimeout(fn,60)}
function install(){installCss();installLongTaskObserver();let tries=0;const attempt=()=>{const a=wrapHistory(),b=wrapStores();if((a||window.ADERENCIA_HISTORY?.__rc42Cached)&&(b||window.ADERENCIA_STORE_REGISTRY?.__rc42Cached)){metrics.lastReadyAt=performance.now();window.ADERENCIA_PERFORMANCE={version:'RC42',metrics,refresh(){wrapHistory();wrapStores()}};window.dispatchEvent(new CustomEvent('aderencia:performance-ready',{detail:{elapsedMs:Math.round(metrics.lastReadyAt-metrics.startedAt)}}));return}if(++tries<40)idle(attempt)};idle(attempt)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',install,{once:true});else install();
})();