(function(){
'use strict';
const DB_NAME='aderenciaPortableDB';
const STORE='handles';
const HANDLE_KEY='portableHistory';
const HISTORY_KEY='aderenciaHistoricoV2';
const DIVERGENCE_KEYS=['aderenciaDivergenciasV1','aderenciaDivergenciasV2','aderenciaDivergencias'];
const ADMIN_KEY='aderenciaAdminConfigV1';
const FILE_VERSION=1;
let handle=null;
let writeQueue=Promise.resolve();
let lastSavedAt=null;
const $=id=>document.getElementById(id);
const supports=()=>('showSaveFilePicker'in window)&&('showOpenFilePicker'in window)&&('indexedDB'in window);
function openDB(){return new Promise((resolve,reject)=>{const r=indexedDB.open(DB_NAME,1);r.onupgradeneeded=()=>{if(!r.result.objectStoreNames.contains(STORE))r.result.createObjectStore(STORE)};r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)})}
async function idbGet(){try{const db=await openDB();return await new Promise((res,rej)=>{const tx=db.transaction(STORE,'readonly'),r=tx.objectStore(STORE).get(HANDLE_KEY);r.onsuccess=()=>res(r.result||null);r.onerror=()=>rej(r.error)})}catch{return null}}
async function idbSet(v){try{const db=await openDB();await new Promise((res,rej)=>{const tx=db.transaction(STORE,'readwrite');tx.objectStore(STORE).put(v,HANDLE_KEY);tx.oncomplete=()=>res();tx.onerror=()=>rej(tx.error)})}catch(e){console.warn('Não foi possível memorizar a base portátil',e)}}
function config(){try{return Object.assign({clearHistoryEnabled:true},JSON.parse(localStorage.getItem(ADMIN_KEY)||'{}'))}catch{return{clearHistoryEnabled:true}}}
function saveConfig(v){localStorage.setItem(ADMIN_KEY,JSON.stringify(v));applyAdmin()}
function collect(){const data={format:'aderencia-escala-portable',version:FILE_VERSION,updatedAt:new Date().toISOString(),history:[],divergences:{},admin:config()};try{data.history=JSON.parse(localStorage.getItem(HISTORY_KEY)||'[]')}catch{}for(const k of DIVERGENCE_KEYS){const raw=localStorage.getItem(k);if(raw!==null){try{data.divergences[k]=JSON.parse(raw)}catch{data.divergences[k]=raw}}}return data}
function validate(data){if(!data||data.format!=='aderencia-escala-portable'||!Array.isArray(data.history))throw new Error('Arquivo não é uma base portátil válida da Aderência de Escala.');return data}
function apply(data){validate(data);localStorage.setItem(HISTORY_KEY,JSON.stringify(data.history||[]));if(data.divergences&&typeof data.divergences==='object')for(const[k,v]of Object.entries(data.divergences))localStorage.setItem(k,typeof v==='string'?v:JSON.stringify(v));if(data.admin&&typeof data.admin==='object')localStorage.setItem(ADMIN_KEY,JSON.stringify(Object.assign({clearHistoryEnabled:true},data.admin)));window.ADERENCIA_HISTORY?.notify?.();window.dispatchEvent(new CustomEvent('aderencia:portableloaded'));applyAdmin()}
async function permission(h,write=false){if(!h)return false;const opts={mode:write?'readwrite':'read'};if(await h.queryPermission(opts)==='granted')return true;return(await h.requestPermission(opts))==='granted'}
function status(text,state='neutral'){const e=$('portableDbStatus');if(!e)return;e.textContent=text;e.dataset.state=state}
async function writeNow(){if(!handle)return false;if(!await permission(handle,true)){status('Base portátil: permissão necessária','warn');return false}const writable=await handle.createWritable();await writable.write(JSON.stringify(collect(),null,2));await writable.close();lastSavedAt=new Date();status(`Base portátil: conectada • salva ${lastSavedAt.toLocaleTimeString('pt-BR',{hour:'2-digit',minute:'2-digit'})}`,'ok');return true}
function scheduleWrite(){if(!handle)return;writeQueue=writeQueue.then(()=>writeNow()).catch(e=>{console.error(e);status('Base portátil: falha ao salvar','error')})}
async function createBase(){if(!supports())return alert('Este navegador não permite gravação direta em arquivo. Use Edge ou Chrome atualizado e mantenha o backup manual disponível.');try{handle=await showSaveFilePicker({suggestedName:'aderencia-dados.json',types:[{description:'Base portátil da Aderência',accept:{'application/json':['.json']}}]});await idbSet(handle);await writeNow()}catch(e){if(e?.name!=='AbortError')alert(`Não foi possível criar a base: ${e.message}`)}}
async function openBase(){if(!supports())return alert('Este navegador não permite vincular arquivo local. Use Edge ou Chrome atualizado.');try{const [h]=await showOpenFilePicker({multiple:false,types:[{description:'Base portátil da Aderência',accept:{'application/json':['.json']}}]});if(!h)return;handle=h;const file=await handle.getFile(),txt=await file.text(),data=validate(JSON.parse(txt));const local=collect(),fileTime=Date.parse(data.updatedAt||0)||0,localTime=Math.max(0,...(local.history||[]).map(r=>Date.parse(r.savedAt||0)||0));if(local.history.length&&fileTime<localTime){if(confirm('Este computador possui histórico mais recente que o arquivo selecionado. Deseja gravar os dados locais na base portátil?'))await writeNow();else apply(data)}else apply(data);await idbSet(handle);lastSavedAt=new Date(file.lastModified);status(`Base portátil: conectada • ${file.name}`,'ok')}catch(e){if(e?.name!=='AbortError')alert(`Não foi possível abrir a base: ${e.message}`)}}
function applyAdmin(){const c=config(),b=$('clearHistoryBtn');if(b){b.hidden=!c.clearHistoryEnabled;b.disabled=!c.clearHistoryEnabled}const f=$('adminClearFlag');if(f)f.checked=!!c.clearHistoryEnabled}
function injectUI(){const hero=document.querySelector('.hero');if(hero&&!$('portableDbPanel')){const box=document.createElement('div');box.id='portableDbPanel';box.className='portable-db-panel';box.innerHTML='<div id="portableDbStatus" class="portable-db-status">Base portátil: não vinculada • dados somente neste computador</div><div class="portable-db-actions"><button id="portableCreateBtn" class="secondary" type="button">Criar base</button><button id="portableOpenBtn" class="secondary" type="button">Vincular base</button><button id="adminMenuBtn" class="secondary" type="button">Administrador</button></div>';hero.appendChild(box)}if(!$('adminModal')){const m=document.createElement('div');m.id='adminModal';m.className='modal-backdrop hidden';m.innerHTML='<div class="modal-card"><h3>Administrador</h3><p>Configurações locais da aplicação. Não há senha.</p><label class="admin-flag"><input id="adminClearFlag" type="checkbox"> Habilitar botão “Limpar histórico”</label><p class="admin-note">Quando desabilitado, o botão é ocultado. O histórico e a base portátil não são apagados.</p><div class="modal-actions"><button id="adminCloseBtn" class="secondary" type="button">Fechar</button></div></div>';document.body.appendChild(m)}$('portableCreateBtn')?.addEventListener('click',createBase);$('portableOpenBtn')?.addEventListener('click',openBase);$('adminMenuBtn')?.addEventListener('click',()=>{$('adminModal').classList.remove('hidden');applyAdmin()});$('adminCloseBtn')?.addEventListener('click',()=>$('adminModal').classList.add('hidden'));$('adminClearFlag')?.addEventListener('change',e=>{saveConfig({clearHistoryEnabled:e.target.checked});scheduleWrite()});applyAdmin()}
function patchStorage(){const original=Storage.prototype.setItem;Storage.prototype.setItem=function(k,v){const r=original.call(this,k,v);if(this===localStorage&&(k===HISTORY_KEY||DIVERGENCE_KEYS.includes(k)||k===ADMIN_KEY))setTimeout(scheduleWrite,0);return r}}
async function restoreRemembered(){if(!supports())return;const h=await idbGet();if(!h)return;handle=h;try{if(await permission(handle,false)){const f=await handle.getFile(),data=validate(JSON.parse(await f.text()));apply(data);lastSavedAt=new Date(f.lastModified);status(`Base portátil: conectada • ${f.name}`,'ok')}else status('Base portátil: clique em Vincular base para autorizar','warn')}catch(e){console.warn(e);handle=null;status('Base portátil: vínculo anterior indisponível','warn')}}
document.addEventListener('DOMContentLoaded',()=>{injectUI();restoreRemembered()});patchStorage();window.addEventListener('aderencia:historychange',scheduleWrite);window.addEventListener('beforeunload',()=>{if(handle)scheduleWrite()});window.ADERENCIA_PORTABLE={createBase,openBase,save:scheduleWrite,config};
})();