(function(){
'use strict';
const DB_NAME='aderenciaPortableDB';
const STORE='handles';
const HANDLE_KEY='portableHistory';
const HISTORY_KEY='aderenciaHistoricoV2';
const DIVERGENCE_KEYS=['aderenciaDivergenciasV1','aderenciaDivergenciasPendentesV1','aderenciaDivergenciasV2','aderenciaDivergencias'];
const ADMIN_KEY='aderenciaAdminConfigV1';
const MODIFIED_KEY='aderenciaPortableModifiedAtV1';
const FILE_VERSION=2;
let handle=null;
let writeQueue=Promise.resolve();
let writeTimer=null;
let applying=false;
const $=id=>document.getElementById(id);
const supports=()=>('showSaveFilePicker'in window)&&('showOpenFilePicker'in window)&&('indexedDB'in window);
function openDB(){return new Promise((resolve,reject)=>{const r=indexedDB.open(DB_NAME,1);r.onupgradeneeded=()=>{if(!r.result.objectStoreNames.contains(STORE))r.result.createObjectStore(STORE)};r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)})}
async function idbGet(){try{const db=await openDB();return await new Promise((res,rej)=>{const tx=db.transaction(STORE,'readonly'),r=tx.objectStore(STORE).get(HANDLE_KEY);r.onsuccess=()=>res(r.result||null);r.onerror=()=>rej(r.error)})}catch{return null}}
async function idbSet(v){try{const db=await openDB();await new Promise((res,rej)=>{const tx=db.transaction(STORE,'readwrite');tx.objectStore(STORE).put(v,HANDLE_KEY);tx.oncomplete=()=>res();tx.onerror=()=>rej(tx.error)})}catch(e){console.warn('Não foi possível memorizar a base portátil',e)}}
function config(){try{return Object.assign({clearHistoryEnabled:true},JSON.parse(localStorage.getItem(ADMIN_KEY)||'{}'))}catch{return{clearHistoryEnabled:true}}}
function localModified(){return Date.parse(localStorage.getItem(MODIFIED_KEY)||'')||0}
function touch(){if(applying)return;try{localStorage.setItem(MODIFIED_KEY,new Date().toISOString())}catch{}}
function saveConfig(v){localStorage.setItem(ADMIN_KEY,JSON.stringify(v));applyAdmin()}
function collect(){const data={format:'aderencia-escala-portable',version:FILE_VERSION,updatedAt:new Date().toISOString(),history:[],divergences:{},admin:config()};try{data.history=JSON.parse(localStorage.getItem(HISTORY_KEY)||'[]')}catch{}for(const k of DIVERGENCE_KEYS){const raw=localStorage.getItem(k);if(raw!==null){try{data.divergences[k]=JSON.parse(raw)}catch{data.divergences[k]=raw}}}return data}
function validate(data){if(!data||data.format!=='aderencia-escala-portable'||!Array.isArray(data.history))throw new Error('Arquivo não é uma base portátil válida da Aderência de Escala.');if(data.version!=null&&Number(data.version)>FILE_VERSION)throw new Error('A base portátil foi criada por uma versão mais nova da aplicação.');return data}
function apply(data){validate(data);applying=true;try{localStorage.setItem(HISTORY_KEY,JSON.stringify(data.history||[]));for(const k of DIVERGENCE_KEYS)localStorage.removeItem(k);if(data.divergences&&typeof data.divergences==='object')for(const[k,v]of Object.entries(data.divergences))if(DIVERGENCE_KEYS.includes(k))localStorage.setItem(k,typeof v==='string'?v:JSON.stringify(v));localStorage.setItem(ADMIN_KEY,JSON.stringify(Object.assign({clearHistoryEnabled:true},data.admin||{})));localStorage.setItem(MODIFIED_KEY,data.updatedAt||new Date().toISOString())}finally{applying=false}window.ADERENCIA_HISTORY?.notify?.();window.dispatchEvent(new CustomEvent('aderencia:portableloaded'));applyAdmin()}
async function queryPermission(h,write=false){if(!h)return'denied';try{return await h.queryPermission({mode:write?'readwrite':'read'})}catch{return'denied'}}
async function requestPermission(h,write=false){if(!h)return false;try{if(await queryPermission(h,write)==='granted')return true;return(await h.requestPermission({mode:write?'readwrite':'read'}))==='granted'}catch{return false}}
function status(text,state='neutral'){const e=$('portableDbStatus');if(!e)return;e.textContent=text;e.dataset.state=state}
async function writeNow(requireGesture=false){if(!handle)return false;const ok=requireGesture?await requestPermission(handle,true):(await queryPermission(handle,true)==='granted');if(!ok){status('Base portátil: clique em Vincular base para autorizar gravação','warn');return false}const writable=await handle.createWritable();await writable.write(JSON.stringify(collect(),null,2));await writable.close();localStorage.setItem(MODIFIED_KEY,new Date().toISOString());status(`Base portátil: conectada • salva ${new Date().toLocaleTimeString('pt-BR',{hour:'2-digit',minute:'2-digit'})}`,'ok');return true}
function scheduleWrite(){if(!handle)return;clearTimeout(writeTimer);writeTimer=setTimeout(()=>{writeQueue=writeQueue.then(()=>writeNow(false)).catch(e=>{console.error(e);status('Base portátil: falha ao salvar','error')})},180)}
async function loadHandle(h,allowChoice=true){const file=await h.getFile(),data=validate(JSON.parse(await file.text())),fileTime=Date.parse(data.updatedAt||0)||0,localTime=localModified();if(allowChoice&&localTime&&fileTime&&localTime>fileTime){const useLocal=confirm('Este computador possui alterações mais recentes que a base selecionada. OK = gravar os dados locais no arquivo. Cancelar = carregar o arquivo e substituir os dados locais.');if(useLocal){handle=h;if(!await writeNow(true))throw new Error('Permissão de gravação não concedida.');return}else apply(data)}else apply(data);handle=h;await idbSet(handle);status(`Base portátil: conectada • ${file.name}`,'ok')}
async function createBase(){if(!supports())return alert('Este navegador não permite gravação direta em arquivo. Use Edge ou Chrome atualizado; o Backup manual continua disponível.');try{const h=await showSaveFilePicker({suggestedName:'aderencia-dados.json',types:[{description:'Base portátil da Aderência',accept:{'application/json':['.json']}}]});handle=h;const existing=await h.getFile();if(existing.size>0&&!confirm('O arquivo selecionado já possui conteúdo. Deseja substituí-lo pelos dados atuais desta aplicação?')){handle=null;return}await idbSet(handle);touch();if(!await writeNow(true))throw new Error('Permissão de gravação não concedida.')}catch(e){if(e?.name!=='AbortError')alert(`Não foi possível criar a base: ${e.message}`)}}
async function openBase(){if(!supports())return alert('Este navegador não permite vincular arquivo local. Use Edge ou Chrome atualizado.');try{if(handle){const perm=await queryPermission(handle,false);if(perm!=='granted'){if(await requestPermission(handle,true)){await loadHandle(handle,true);return}}else{await loadHandle(handle,true);return}}const [h]=await showOpenFilePicker({multiple:false,types:[{description:'Base portátil da Aderência',accept:{'application/json':['.json']}}]});if(h)await loadHandle(h,true)}catch(e){if(e?.name!=='AbortError')alert(`Não foi possível abrir a base: ${e.message}`)}}
function applyAdmin(){const c=config(),b=$('clearHistoryBtn');if(b){b.hidden=!c.clearHistoryEnabled;b.disabled=!c.clearHistoryEnabled}const f=$('adminClearFlag');if(f)f.checked=!!c.clearHistoryEnabled}
function injectStyles(){if($('portableStorageStyles'))return;const s=document.createElement('style');s.id='portableStorageStyles';s.textContent='.portable-db-panel{margin-left:auto;display:flex;flex-direction:column;align-items:flex-end;gap:6px;min-width:330px}.portable-db-status{font-size:9px;color:#66768a;text-align:right}.portable-db-status[data-state="ok"]{color:#18794e}.portable-db-status[data-state="warn"]{color:#9a6300}.portable-db-status[data-state="error"]{color:#b42318}.portable-db-actions{display:flex;gap:6px;flex-wrap:wrap;justify-content:flex-end}.portable-db-actions button{padding:7px 10px;font-size:9px}.admin-flag{display:flex;gap:9px;align-items:center;margin:14px 0;font-size:12px;font-weight:700}.admin-note{font-size:10px;color:#718096}@media(max-width:980px){.hero{flex-wrap:wrap}.portable-db-panel{width:100%;align-items:flex-start}.portable-db-status{text-align:left}.portable-db-actions{justify-content:flex-start}}';document.head.appendChild(s)}
function injectUI(){injectStyles();const hero=document.querySelector('.hero');if(hero&&!$('portableDbPanel')){const box=document.createElement('div');box.id='portableDbPanel';box.className='portable-db-panel';box.innerHTML='<div id="portableDbStatus" class="portable-db-status">Base portátil: não vinculada • dados somente neste computador</div><div class="portable-db-actions"><button id="portableCreateBtn" class="secondary" type="button">Criar base</button><button id="portableOpenBtn" class="secondary" type="button">Vincular base</button><button id="adminMenuBtn" class="secondary" type="button">Administrador</button></div>';hero.appendChild(box)}if(!$('adminModal')){const m=document.createElement('div');m.id='adminModal';m.className='modal-backdrop hidden';m.innerHTML='<div class="modal-card"><h3>Administrador</h3><p>Configurações locais da aplicação. Não há senha.</p><label class="admin-flag"><input id="adminClearFlag" type="checkbox"> Habilitar botão “Limpar histórico”</label><p class="admin-note">Quando desabilitado, o botão é ocultado. O histórico e a base portátil permanecem intactos.</p><div class="modal-actions"><button id="adminCloseBtn" class="secondary" type="button">Fechar</button></div></div>';document.body.appendChild(m)}$('portableCreateBtn')?.addEventListener('click',createBase);$('portableOpenBtn')?.addEventListener('click',openBase);$('adminMenuBtn')?.addEventListener('click',()=>{$('adminModal').classList.remove('hidden');applyAdmin()});$('adminCloseBtn')?.addEventListener('click',()=>$('adminModal').classList.add('hidden'));$('adminClearFlag')?.addEventListener('change',e=>{saveConfig({clearHistoryEnabled:e.target.checked});scheduleWrite()});applyAdmin()}
function patchStorage(){if(window.__ADERENCIA_STORAGE_PATCHED__)return;window.__ADERENCIA_STORAGE_PATCHED__=true;const original=Storage.prototype.setItem;Storage.prototype.setItem=function(k,v){const r=original.call(this,k,v);if(this===localStorage&&(k===HISTORY_KEY||DIVERGENCE_KEYS.includes(k)||k===ADMIN_KEY)){if(k===HISTORY_KEY){try{const parsed=JSON.parse(v);if(Array.isArray(parsed)&&parsed.length===0)for(const dk of DIVERGENCE_KEYS)original.call(this,dk,'[]')}catch{}}touch();scheduleWrite()}return r}}
async function restoreRemembered(){if(!supports()){status('Base portátil automática indisponível neste navegador • use Backup/Restaurar','warn');return}const h=await idbGet();if(!h)return;handle=h;try{if(await queryPermission(handle,false)==='granted'){await loadHandle(handle,false)}else status('Base portátil conhecida • clique em Vincular base para autorizar','warn')}catch(e){console.warn(e);status('Base portátil anterior indisponível • vincule novamente','warn')}}
document.addEventListener('DOMContentLoaded',()=>{injectUI();restoreRemembered()});patchStorage();window.addEventListener('aderencia:historychange',scheduleWrite);window.ADERENCIA_PORTABLE={createBase,openBase,save:()=>writeNow(true),config};
})();